import { TransmissionMachine } from './engine.js?v=4.5.0';
import { profile, projects, skills, achievements, realms } from './data.js?v=4.5.0';

const $=(q,p=document)=>p.querySelector(q), $$=(q,p=document)=>[...p.querySelectorAll(q)];
const root=document.documentElement, body=document.body;
const canvas=$('#webgl'), boot=$('#boot'), lens=$('#lens'), lensContent=$('#lens-content');
const transition=$('#transition'), transitionWord=$('#transition-word'), transitionKicker=$('#transition-kicker');
const mapOverlay=$('#map'), mapLabels=$('#map-labels'), commandOverlay=$('#command'), commandInput=$('#command-input'), commandResults=$('#command-results'), searchEcho=$('#search-echo'), cursorPulses=$('#cursor-pulses');
const soundtrack=$('#soundtrack'), volume=$('#volume'), soundBtn=$('#sound-btn');
let engine=null,current='home',overlayReturn='home',tourTimer=null,tourOn=false,focusMode=false,explodeOn=false,inspectMode=false;
let audioCtx=null,source=null,analyser=null,master=null,filter=null,freqData=null,soundStarted=false,muted=false,selectedSearch=0,searchItems=[];

const routeName=route=>{
  if(route.startsWith('project/'))return projects.find(p=>route===`project/${p.slug}`)?.name||'PROJECT';
  return {home:'ORIGIN',projects:'ARCHIVE',cyber:'BREACH',about:'ORBIT',contact:'UPLINK',lab:'FORGE',timeline:'TRAJECTORY',map:'ATLAS',search:'SEARCH ARRAY'}[route]||route.toUpperCase();
};
const routeMeta=route=>{
  if(route.startsWith('project/')){const p=projects.find(p=>route===`project/${p.slug}`);return {num:p?.label?.slice(0,2)||'01',code:p?.name?.toUpperCase()||'PROJECT'};}
  return {home:{num:'00',code:'ORIGIN'},projects:{num:'01',code:'ARCHIVE'},cyber:{num:'02',code:'BREACH'},about:{num:'03',code:'ORBIT'},contact:{num:'04',code:'UPLINK'},lab:{num:'05',code:'FORGE'},timeline:{num:'06',code:'TRAJECTORY'}}[route]||{num:'--',code:'SIGNAL'};
};}
  return {home:{num:'00',code:'ORIGIN'},projects:{num:'01',code:'ARCHIVE'},cyber:{num:'02',code:'BREACH'},about:{num:'03',code:'ORBIT'},contact:{num:'04',code:'UPLINK'}}[route]||{num:'--',code:'SIGNAL'};
};
const paletteFor=route=>{
  const p=route.startsWith('project/')?projects.find(x=>route===`project/${x.slug}`):null;
  if(p){if(p.realm==='ruvigil')return ['#47f5ff','#c67a24','#e7fff9'];if(p.realm==='phantom')return ['#ff5bd7','#6d44ff','#dffff4'];if(p.realm==='elif')return ['#b9ff43','#ff5038','#eef9ce'];return [p.accent,'#754dff','#fff4d5'];}
  return {home:['#ff8552','#ff2ea6','#4df1ff'],projects:['#ff2ea6','#19e6ff','#fff4cb'],cyber:['#faff00','#ff5a1f','#f3ffc0'],about:['#ffd87a','#7d52ff','#a9ffe6'],contact:['#88ffd5','#ff9b78','#e6e0ff'],lab:['#34f0ff','#b5ff5b','#ffe78a'],timeline:['#ff8bc2','#6cf2ff','#f8f4db'],map:['#6ce8ff','#ff5d98','#fff0ae'],search:['#ffffff','#ff5d98','#6ce8ff']}[route]||['#ff8552','#ff2ea6','#4df1ff'];
};
function setPalette(route){const [a,b,c]=paletteFor(route);root.style.setProperty('--a',a);root.style.setProperty('--b',b);root.style.setProperty('--c',c);}
function lensSide(route){if(route==='projects'||route==='about'||route==='lab')return 'right';if(route==='contact'||route==='timeline')return 'center';return 'left';}
function setLensSide(side){lens.classList.remove('lens-left','lens-right','lens-center');lens.classList.add(`lens-${side}`);}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
const skillGroups=()=>{const g=new Map();skills.forEach(s=>{const k=s.family||'Systems';if(!g.has(k))g.set(k,[]);g.get(k).push(s)});return [...g.entries()];};

function homeHTML(){return `
  <div class="kicker">ORIGIN / CYBERPUNK TRANSMISSION · BUILD 4.5</div>
  <h1>Build.<span class="spectral">Break. Evolve.</span></h1>
  <p class="lead">I’m ${esc(profile.name)} — building systems that feel alive, inspecting how they truly behave, and turning hardware, code, AI and low-level security into one cinematic machine language.</p>
  <div class="hero-panels">
    <section><small>PRIMARY VECTOR</small><b>Robotics / Embedded</b><span>Sensors · firmware · interaction</span></section>
    <section><small>SECOND VECTOR</small><b>AI / Vision</b><span>Perception · learning · behavior</span></section>
    <section><small>THIRD VECTOR</small><b>Reverse / Pwn / CTF</b><span>Analysis · exploitation · understanding</span></section>
  </div>
  <div class="signal-stats">
    <div><small>ACTIVE PROJECTS</small><b>${projects.length}</b></div>
    <div><small>CAPABILITY REALMS</small><b>${realms.length}</b></div>
    <div><small>FOCUS THREADS</small><b>${profile.focus.length}</b></div>
  </div>
  <div class="actions"><button class="action primary magnetic" data-route="projects">ENTER ARCHIVE →</button><button class="action magnetic" data-route="lab">OPEN FORGE ↗</button><a class="action magnetic" href="${profile.links.github}" target="_blank" rel="noreferrer">GITHUB ↗</a></div>
  <div class="frequency-strip" aria-hidden="true">${Array.from({length:28},(_,i)=>`<i style="--i:${i};--h:${18+(i*31)%82}%"></i>`).join('')}</div>`;}
function projectsHTML(){return `
  <div class="kicker">PROJECT CONSTELLATION / LIVE SIGNALS</div>
  <h2>Archive of<br><span class="spectral">built things.</span></h2>
  <p class="lead">Each project has its own machine state. Select a transmission and the entire 3D field reconfigures around it.</p>
  <div class="project-list">${projects.map((p,i)=>`<button class="project-row magnetic" type="button" data-route="project/${p.slug}" style="--project:${p.accent}"><span class="n">${String(i+1).padStart(2,'0')}</span><span class="project-copy"><small>${esc(p.label)}</small><b>${esc(p.name)}</b><p>${esc(p.tagline)}</p></span><span class="signal-mark"><i></i><b>OPEN</b></span></button>`).join('')}</div>`;}

function projectHTML(route){const p=projects.find(x=>route===`project/${x.slug}`);if(!p)return projectsHTML();return `
  <div class="project-head"><div><div class="kicker">${esc(p.label)}</div><h2>${esc(p.name)}</h2><p class="lead">${esc(p.tagline)}</p></div><span class="project-status">${esc(p.status)}</span></div>
  <div class="project-visual"><img src="${p.poster}" alt="${esc(p.name)} project artwork"><div class="project-scan"></div><small>LIVE PROJECT SIGNAL / ${esc(p.year)}</small></div>
  <p class="project-desc">${esc(p.long)}</p>
  <div class="tag-cloud">${p.stack.map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div>
  <div class="project-facts"><div><small>ROLE</small><b>${esc(p.role)}</b></div><div><small>YEAR</small><b>${esc(p.year)}</b></div><div><small>STATE</small><b>${esc(p.status)}</b></div></div>
  <div class="actions"><a class="action primary magnetic" href="${p.repository}" target="_blank" rel="noreferrer">REPOSITORY ↗</a><button class="action magnetic" data-route="projects">← ARCHIVE</button></div>`;}

function cyberHTML(){return `
  <div class="kicker">BREACH STATE / LOW-LEVEL SIGNAL</div>
  <h2>Take it apart.<br><span class="spectral">Know it better.</span></h2>
  <p class="lead">Reverse engineering, binary exploitation and forensics turn software into something observable instead of mysterious. CTFs make that curiosity measurable under pressure.</p>
  <div class="terminal"><div class="terminal-head"><i></i><i></i><i></i><span>root@0xaeternova // live</span></div><pre><span class="p">root@0xaeternova:~#</span> whoami
robotics_ai + reverse_engineering + pwn

<span class="p">root@0xaeternova:~#</span> team
GeomRavage

<span class="p">root@0xaeternova:~#</span> methodology
observe → disassemble → exploit → understand → rebuild █</pre></div>
  <div class="achievement-stack">${achievements.map(a=>`<a href="${a.url}" target="_blank" rel="noreferrer"><small>VERIFIED SIGNAL</small><b>${esc(a.title)} ↗</b><p>${esc(a.text)}</p></a>`).join('')}</div>
  <div class="actions"><a class="action primary" href="${profile.links.ctftime}" target="_blank" rel="noreferrer">CTFTIME ↗</a><a class="action" href="${profile.links.team}" target="_blank" rel="noreferrer">GEOMRAVAGE ↗</a></div>`;}

function aboutHTML(){return `
  <div class="about-grid about-grid-v45">
    <div class="about-portrait hero-upgrade"><div class="hero-frame"><img src="assets/profile/profile-hero-dark.svg" alt="0xAeterNova GitHub profile hero"><div class="portrait-scan"></div><div class="hero-glow"></div></div><span>IDENTITY SIGNAL // 0xAeterNova</span></div>
    <div class="about-copy"><div class="kicker">ORBIT / IDENTITY ARCHITECTURE</div><h2>Machines are the medium.<br><span class="spectral">Curiosity is the engine.</span></h2><p class="lead">I work where robotics, perception, embedded systems, AI and low-level security collide. What matters is not performative scoring — it is how far I can follow a system until its behavior becomes legible, usable and worth reinventing.</p><div class="identity-signature"><span>BUILD</span><i></i><span>DISASSEMBLE</span><i></i><span>UNDERSTAND</span><i></i><span>REINVENT</span></div><div class="about-pillars"><span>Real systems</span><span>Iterative research</span><span>Security thinking</span><span>Interactive design</span></div></div>
  </div>
  <div class="identity-modules"><section><small>CURRENT FOCUS</small><b>Immersive interfaces + sensing systems</b><p>Turning technical work into experiences that feel alive and readable.</p></section><section><small>WORKFLOW</small><b>Build → observe → break → rebuild</b><p>Prototype fast, inspect deeply, then return with sharper constraints and stronger architecture.</p></section><section><small>LOCATION / MODE</small><b>${esc(profile.location)} · experimental systems</b><p>Robotics, AI, embedded systems, low-level security and realtime visual interfaces.</p></section></div>
  <div class="capability-atlas">${skillGroups().slice(0,6).map(([family,items],i)=>`<section class="capability-cluster" style="--cluster:${i}"><small>${esc(family)}</small><div>${items.slice(0,6).map(x=>`<span><b>${esc(x.name)}</b><em>${esc(x.signal||'active discipline')}</em></span>`).join('')}</div></section>`).join('')}</div>
  <div class="identity-manifesto"><div><small>01 / BUILD</small><b>Make the idea touch reality.</b><p>Prototype with real sensors, devices, code and constraints.</p></div><div><small>02 / BREAK</small><b>Inspect below the abstraction.</b><p>Reverse, trace, test and learn what the system is actually doing.</p></div><div><small>03 / EVOLVE</small><b>Rebuild with better understanding.</b><p>Turn what was learned into a cleaner, stranger and stronger next version.</p></div></div>`;}
function labHTML(){return `
  <div class="kicker">FORGE DISTRICT / PROTOTYPE HANGAR</div>
  <h2>Invent strange things.<br><span class="spectral">Then make them real.</span></h2>
  <p class="lead">The Forge is where experiments, interface studies, embedded builds and realtime visual systems are treated like test rigs instead of static portfolio items.</p>
  <div class="lab-grid"><section><small>NOW BUILDING</small><b>Immersive WebGL portfolio architecture</b><p>Self-contained realtime rendering, adaptive performance, local assets, and world-state transitions.</p></section><section><small>TOOLS</small><b>Rust / Python / C++ / JS</b><p>Tooling moves between firmware, AI, graphics, automation and low-level analysis.</p></section><section><small>INTERACTION</small><b>Sensors + signals + UI</b><p>Experiments focus on interfaces that feel responsive, legible and cinematic.</p></section><section><small>LAB MODE</small><b>Prototype aggressively</b><p>Fast iteration, test in motion, keep the surprising parts.</p></section></div>
  <div class="actions"><button class="action primary magnetic" data-route="timeline">SEE TRAJECTORY →</button><button class="action magnetic" data-route="projects">OPEN ARCHIVE ↗</button></div>`;}

function timelineHTML(){return `
  <div class="kicker">TRAJECTORY / SIGNAL TIMELINE</div>
  <h2>Where the machine<br><span class="spectral">has been heading.</span></h2>
  <p class="lead">A compressed view of the path so far — from curiosity and CTF pressure to robotics, AI systems, sensing research and custom environments.</p>
  <div class="timeline-rail"><article><small>PHASE 01</small><b>Security curiosity</b><p>Reverse engineering, pwn, forensics and CTF work established the habit of going beneath the surface.</p></article><article><small>PHASE 02</small><b>Robotics + AI</b><p>Physical systems, sensing, machine perception and intelligent control became the primary build vector.</p></article><article><small>PHASE 03</small><b>Experimental systems</b><p>Projects like RuVigil, PHANTOM and Elif turned technical interests into complete signals.</p></article><article><small>PHASE 04</small><b>Realtime interfaces</b><p>Portfolio design itself becomes another machine: audiovisual, spatial, interactive and alive.</p></article></div>
  <div class="actions"><button class="action primary magnetic" data-route="about">IDENTITY ORBIT →</button><button class="action magnetic" data-route="home">RETURN ORIGIN ↗</button></div>`;}

function contactHTML(){const links=[['GitHub',profile.links.github,'CODE / PROJECTS'],['LinkedIn',profile.links.linkedin,'PROFESSIONAL'],['CTFtime',profile.links.ctftime,'COMPETITION'],['GeomRavage',profile.links.team,'TEAM'],['LinkTree',profile.links.linktree,'ALL CHANNELS'],['Telegram',profile.links.telegram,'DIRECT SIGNAL']];return `
  <div class="kicker">AURORA UPLINK / OPEN CHANNEL</div>
  <h2>Transmit<br><span class="spectral">a signal.</span></h2>
  <p class="lead">Robotics, AI, embedded systems, competitions, reverse engineering, research or strange technical ideas — choose a channel and send it.</p>
  <div class="contact-grid">${links.map((x,i)=>`<a class="contact-tile magnetic" href="${x[1]}" target="_blank" rel="noreferrer" style="--delay:${i*45}ms"><small>${esc(x[2])}</small><b>${esc(x[0])}<span>↗</span></b><i></i></a>`).join('')}</div>`;}

function renderLens(route){const meta=routeMeta(route);$('#lens-num').textContent=meta.num;$('#lens-code').textContent=meta.code;setLensSide(lensSide(route));if(route==='home')lensContent.innerHTML=homeHTML();else if(route==='projects')lensContent.innerHTML=projectsHTML();else if(route==='cyber')lensContent.innerHTML=cyberHTML();else if(route==='about')lensContent.innerHTML=aboutHTML();else if(route==='contact')lensContent.innerHTML=contactHTML();else if(route==='lab')lensContent.innerHTML=labHTML();else if(route==='timeline')lensContent.innerHTML=timelineHTML();else if(route.startsWith('project/'))lensContent.innerHTML=projectHTML(route);$('#telemetry-field').textContent=routeName(route);$$('.phase-node').forEach(n=>n.classList.toggle('active',route===n.dataset.route||(route.startsWith('project/')&&n.dataset.route==='projects')));}

function buildDial(){const dial=$('#phase-dial');dial.innerHTML=realms.map(r=>`<button class="phase-node magnetic" type="button" data-route="${r.id}" title="${r.name}"><span>${r.number}</span><b class="phase-label">${r.name}</b></button>`).join('');}
function transitionTo(route){transitionWord.textContent=routeName(route);transitionKicker.textContent=route.startsWith('project/')?'LOCKING PROJECT SIGNAL':'TRANSMITTING';transition.classList.remove('active');void transition.offsetWidth;transition.classList.add('active');setTimeout(()=>transition.classList.remove('active'),1180);}
function navigate(route,{instant=false,hash=true}={}){if(!engine||!engine.scenes?.[route])return;if(route===current&&!instant)return;closeMap(false);closeSearch(false);const from=current;current=route;setPalette(route);renderLens(route);if(!instant)transitionTo(route);lens.classList.add('switching');setTimeout(()=>{engine.setRoute(route,instant);lens.classList.remove('switching')},instant?0:220);if(hash)history.replaceState(null,'','#'+(route.startsWith('project/')?'project/'+route.slice(8):route));txSweep(from,route);}

function routeFromHash(){const h=location.hash.replace(/^#/,'');if(h.startsWith('project/'))return `project/${h.slice(8)}`;return ['home','projects','cyber','about','contact','lab','timeline'].includes(h)?h:'home';}

function mapLabelName(route){if(route.startsWith('project/'))return projects.find(p=>route===`project/${p.slug}`)?.name||'Project';return {home:'Origin',projects:'Archive',cyber:'Breach',about:'Orbit',contact:'Uplink',lab:'Forge',timeline:'Trajectory'}[route]||route;}
function openMap(){if(!engine)return;overlayReturn=current;mapOverlay.hidden=false;body.classList.add('map-active');setPalette('map');engine.setRoute('map');const routes=['home','projects','cyber','about','contact','lab','timeline',...projects.map(p=>`project/${p.slug}`)];$('#atlas-node-count').textContent=`${String(routes.length).padStart(2,'0')} SIGNALS`;mapLabels.innerHTML=routes.map((r,i)=>`<button class="map-node-label ${r.startsWith('project/')?'project-node':'core-node'}" data-route="${r}" data-map-route="${r}" style="--node-index:${i}"><span class="map-pin"><i></i></span><small>${r.startsWith('project/')?'PROJECT TRANSMISSION':'CORE MACHINE STATE'}</small><b>${esc(mapLabelName(r))}</b><em>LOCK ↗</em></button>`).join('');engine.setMapFocus?.(null);}
function closeMap(restore=true){if(mapOverlay.hidden)return;mapOverlay.hidden=true;mapLabels.innerHTML='';body.classList.remove('map-active');if(restore&&engine){setPalette(overlayReturn);engine.setRoute(overlayReturn,true);}}
function updateMapLabels(anchors){if(mapOverlay.hidden)return;const marginX=innerWidth<760?58:110,marginY=innerWidth<760?76:98;const pts=anchors.filter(a=>a.pos.visible).map(a=>({a,x:clamp(a.pos.x,marginX,innerWidth-marginX),y:clamp(a.pos.y,marginY,innerHeight-marginY),z:a.pos.z||0}));for(let pass=0;pass<7;pass++)for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){let dx=pts[j].x-pts[i].x,dy=pts[j].y-pts[i].y,d=Math.hypot(dx,dy)||1;const minD=innerWidth<760?82:146;if(d<minD){const push=(minD-d)*.29,ux=dx/d,uy=dy/d;pts[i].x-=ux*push;pts[i].y-=uy*push;pts[j].x+=ux*push;pts[j].y+=uy*push;}}anchors.forEach(a=>{const el=$(`[data-map-route="${CSS.escape(a.route)}"]`,mapLabels);if(!el)return;const p=pts.find(x=>x.a.route===a.route);el.classList.toggle('behind',!p);if(!p)return;const depth=clamp(1.08-(p.z+1)*.13,.72,1.08);el.style.left=`${clamp(p.x,marginX,innerWidth-marginX)}px`;el.style.top=`${clamp(p.y,marginY,innerHeight-marginY)}px`;el.style.setProperty('--depth',depth.toFixed(3));el.style.zIndex=String(Math.round(60-depth*20));});}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}

function openSearch(){if(!engine)return;overlayReturn=current;commandOverlay.hidden=false;body.classList.add('search-active');setPalette('search');engine.setRoute('search');commandInput.value='';selectedSearch=0;engine.setSearchQuery?.('');renderSearch();setTimeout(()=>commandInput.focus(),80);}
function closeSearch(restore=true){if(commandOverlay.hidden)return;commandOverlay.hidden=true;body.classList.remove('search-active');if(restore&&engine){setPalette(overlayReturn);engine.setRoute(overlayReturn,true);}}
function renderSearch(){const q=commandInput.value.trim();searchItems=engine.search(q);selectedSearch=searchItems.length?Math.max(0,Math.min(selectedSearch,Math.min(2,searchItems.length-1))):0;engine.setSearchQuery?.(q);engine.setSearchResults(searchItems);engine.setSearchFocus?.(selectedSearch);const state=i=>i===0?'PRIMARY LOCK':i===1?'SECONDARY ECHO':'TRACE SIGNAL';commandResults.innerHTML=searchItems.slice(0,3).map((x,i)=>`<button class="command-item${i===selectedSearch?' active':''}" type="button" data-result="${i}"><span class="result-index">0${i+1}</span><span class="result-copy"><small>${esc(x.type||'SIGNAL')}</small><b>${esc(x.label)}</b><em>${esc((x.keywords||'').split(' ').slice(0,4).join(' · '))}</em></span><strong>${i===selectedSearch?'LOCKED':state(i)}</strong></button>`).join('')||`<div class="search-empty"><b>NO RESONANCE</b><span>Try another project, technology, skill or realm.</span></div>`;searchEcho.textContent=q?`${q.toUpperCase()} // ${searchItems.length||0} RESONANCE${searchItems.length===1?'':'S'}`:'AWAITING SIGNAL';}
function commitSearch(i=selectedSearch){const hit=searchItems[i];if(!hit)return;closeSearch(false);current=overlayReturn;engine.setRoute(overlayReturn,true);navigate(hit.route);}

async function startSound(){try{if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();source=audioCtx.createMediaElementSource(soundtrack);filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=15500;const comp=audioCtx.createDynamicsCompressor();comp.threshold.value=-14;comp.knee.value=16;comp.ratio.value=2.5;comp.attack.value=.006;comp.release.value=.26;analyser=audioCtx.createAnalyser();analyser.fftSize=256;analyser.smoothingTimeConstant=.8;master=audioCtx.createGain();master.gain.value=Number(volume.value)/100;source.connect(filter);filter.connect(comp);comp.connect(analyser);analyser.connect(master);master.connect(audioCtx.destination);freqData=new Uint8Array(analyser.frequencyBinCount);}if(audioCtx.state==='suspended')await audioCtx.resume();soundtrack.volume=1;await soundtrack.play();soundStarted=true;muted=false;soundBtn.textContent='♪';}catch(e){console.warn('Soundtrack start failed',e);toast('AUDIO COULD NOT START — CLICK ♪ TO RETRY');}}
function setVolume(v){if(master&&audioCtx)master.gain.setTargetAtTime(v,audioCtx.currentTime,.035);else soundtrack.volume=v;}
function toggleSound(){if(!soundStarted){startSound();return;}muted=!muted;if(master&&audioCtx)master.gain.setTargetAtTime(muted?0:Number(volume.value)/100,audioCtx.currentTime,.045);else soundtrack.muted=muted;soundBtn.textContent=muted?'×':'♪';}
function audioLevel(){if(!analyser||!freqData)return 0;analyser.getByteFrequencyData(freqData);let sum=0,n=0;for(let i=1;i<45;i++){sum+=freqData[i];n++;}return Math.min(1,(sum/n)/170);}
function txSweep(){if(!audioCtx||!soundStarted||muted)return;try{const t=audioCtx.currentTime;const osc=audioCtx.createOscillator(),g=audioCtx.createGain(),pan=audioCtx.createStereoPanner();osc.type='sine';osc.frequency.setValueAtTime(135,t);osc.frequency.exponentialRampToValueAtTime(880,t+.48);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.055,t+.08);g.gain.exponentialRampToValueAtTime(.0001,t+.6);pan.pan.setValueAtTime(-.65,t);pan.pan.linearRampToValueAtTime(.65,t+.6);osc.connect(g);g.connect(pan);pan.connect(master);osc.start(t);osc.stop(t+.62);filter?.frequency.cancelScheduledValues(t);filter?.frequency.setValueAtTime(filter.frequency.value,t);filter?.frequency.exponentialRampToValueAtTime(1500,t+.16);filter?.frequency.exponentialRampToValueAtTime(15500,t+.75);}catch{}}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1800);}

function startTour(){if(tourOn){tourOn=false;clearInterval(tourTimer);$('#tour-btn').classList.remove('on');$('#tour-btn').textContent='AUTOPILOT';return;}tourOn=true;$('#tour-btn').classList.add('on');$('#tour-btn').textContent='STOP TOUR';const sequence=['home','projects','project/ruvigil','project/phantom','project/elif-linux','cyber','lab','timeline','about','contact'];let i=Math.max(0,sequence.indexOf(current));navigate(sequence[i],{instant:true});tourTimer=setInterval(()=>{if(!tourOn)return;i=(i+1)%sequence.length;navigate(sequence[i]);},7200);}
function enter(withSound){if(withSound)startSound();boot.classList.add('leaving');setTimeout(()=>boot.hidden=true,1150);}
window.AeterNovaEnter=enter;window.dispatchEvent(new Event('aeter-app-ready'));

function bindUI(){document.addEventListener('click',e=>{const route=e.target.closest('[data-route]')?.dataset.route;if(route){if(!mapOverlay.hidden&&e.target.closest('.map-node-label')){closeMap(false);current=overlayReturn;engine.setRoute(overlayReturn,true);}navigate(route);return;}const close=e.target.closest('[data-close]')?.dataset.close;if(close==='map')closeMap(true);if(close==='search')closeSearch(true);const ri=e.target.closest('[data-result]')?.dataset.result;if(ri!=null)commitSearch(Number(ri));});
  $('#map-btn').addEventListener('click',openMap);$('#command-btn').addEventListener('click',openSearch);const toggleExplode=()=>{explodeOn=engine.toggleExplode();const btn=$('#explode-btn'),hud=$('#disassembly-hud');btn.classList.toggle('on',explodeOn);btn.textContent=explodeOn?'CLOSE X-RAY':'X-RAY MACHINE';hud.hidden=!explodeOn;body.classList.toggle('explode-mode',explodeOn);$('#lens-hint').textContent=explodeOn?'ENGINEERING X-RAY · DRAG TO INSPECT SHELLS · X TO CLOSE':'DRAG SPACE · SCROLL DEPTH · CLICK SIGNALS';toast(explodeOn?'X-RAY OPEN: MACHINE SYSTEMS SEPARATED':'X-RAY CLOSED: MACHINE REASSEMBLED');};$('#explode-btn').addEventListener('click',toggleExplode);$('#tour-btn').addEventListener('click',startTour);soundBtn.addEventListener('click',toggleSound);volume.addEventListener('input',e=>{setVolume(Number(e.target.value)/100);if(muted)toggleSound();});commandInput.addEventListener('input',()=>{selectedSearch=0;renderSearch();});commandResults.addEventListener('pointerover',e=>{const item=e.target.closest('[data-result]');if(!item)return;selectedSearch=Number(item.dataset.result);engine.setSearchFocus?.(selectedSearch);$$('.command-item',commandResults).forEach((x,i)=>x.classList.toggle('active',i===selectedSearch));});
  addEventListener('keydown',e=>{if(e.key==='/'&&commandOverlay.hidden&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();openSearch();return;}if(e.key==='Escape'){if(!commandOverlay.hidden)closeSearch(true);else if(!mapOverlay.hidden)closeMap(true);return;}if(!commandOverlay.hidden){if(e.key==='ArrowDown'){e.preventDefault();selectedSearch=Math.min(2,selectedSearch+1);renderSearch();}if(e.key==='ArrowUp'){e.preventDefault();selectedSearch=Math.max(0,selectedSearch-1);renderSearch();}if(e.key==='Enter'){e.preventDefault();commitSearch();}return;}if(e.key.toLowerCase()==='m'){e.preventDefault();openMap();}if(e.key.toLowerCase()==='x'){e.preventDefault();toggleExplode();}if(e.key.toLowerCase()==='r'){engine.reset();toast('CAMERA RECENTERED');}if(e.key.toLowerCase()==='f'){focusMode=!focusMode;body.classList.toggle('focus-mode',focusMode);}if(e.key==='1')navigate('home');if(e.key==='2')navigate('projects');if(e.key==='3')navigate('cyber');if(e.key==='4')navigate('about');if(e.key==='5')navigate('contact');if(e.key==='6')navigate('lab');if(e.key==='7')navigate('timeline');});
  const cursor=$('#cursor'),trail=$('#cursor-trail'),lock=$('#cursor-lock');const dots=Array.from({length:9},(_,i)=>{const d=document.createElement('i');d.style.setProperty('--trail-index',i);trail.appendChild(d);return {el:d,x:innerWidth/2,y:innerHeight/2}});let cx=innerWidth/2,cy=innerHeight/2,tx=cx,ty=cy,lastX=cx,lastY=cy,angle=0;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY;const dx=tx-lastX,dy=ty-lastY,speed=Math.min(1,Math.hypot(dx,dy)/45);if(Math.abs(dx)+Math.abs(dy)>2)angle=Math.atan2(dy,dx);root.style.setProperty('--cursor-speed',speed.toFixed(3));root.style.setProperty('--cursor-angle',`${angle}rad`);lastX=tx;lastY=ty;});addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;const p=document.createElement('i');p.style.left=e.clientX+'px';p.style.top=e.clientY+'px';cursorPulses.appendChild(p);setTimeout(()=>p.remove(),780);});const cursorLoop=()=>{cx+=(tx-cx)*.26;cy+=(ty-cy)*.26;cursor.style.transform=`translate(${cx}px,${cy}px)`;let px=cx,py=cy;dots.forEach((d,i)=>{const k=.24-i*.017;d.x+=(px-d.x)*Math.max(.055,k);d.y+=(py-d.y)*Math.max(.055,k);d.el.style.transform=`translate(${d.x}px,${d.y}px) scale(${1-i*.075})`;px=d.x;py=d.y;});requestAnimationFrame(cursorLoop)};cursorLoop();
  document.addEventListener('pointerover',e=>{const target=e.target.closest('button,a,input');const hot=!!target;body.classList.toggle('cursor-hot',hot);body.classList.toggle('cursor-input',!!e.target.closest('input'));lock.textContent=e.target.closest('.map-node-label')?'NODE':e.target.closest('.command-item')?'SIGNAL':e.target.closest('input')?'TYPE':hot?'LOCK':'SCAN';const mapNode=e.target.closest('.map-node-label');if(mapNode&&!mapOverlay.hidden){engine.setMapFocus?.(mapNode.dataset.mapRoute);$('#map-focus-name').textContent=mapLabelName(mapNode.dataset.mapRoute).toUpperCase();$('#map-focus-meta').textContent=mapNode.dataset.mapRoute.startsWith('project/')?'PROJECT TRANSMISSION READY':'CORE STATE // ROUTE READY';}});document.addEventListener('pointerout',e=>{const node=e.target.closest('.map-node-label');if(node&&!mapOverlay.hidden&&!node.contains(e.relatedTarget)){engine.setMapFocus?.(null);$('#map-focus-name').textContent='NO TARGET';$('#map-focus-meta').textContent='MOVE THROUGH THE FIELD';}});
}

function init(){buildDial();bindUI();try{engine=new TransmissionMachine(canvas);console.info('AETER/NOVA TRANSMISSION MACHINE V4.5 // NEON EXODUS');$('#lens-status').textContent='LOCAL 3D // V4.5 ONLINE';engine.onNavigate=route=>{if(!mapOverlay.hidden){closeMap(false);current=overlayReturn;engine.setRoute(overlayReturn,true);}navigate(route);};engine.onHover=route=>{$('#lens-hint').textContent=route?`CLICK TO TRANSMIT // ${routeName(route)}`:'DRAG SPACE · SCROLL DEPTH · CLICK SIGNALS';};engine.onFrame=f=>{$('#telemetry-phase').textContent=f.time.toFixed(3);updateMapLabels(f.map||[]);const lvl=audioLevel();engine.setAudioLevel(lvl);root.style.setProperty('--audio-level',lvl.toFixed(3));root.style.setProperty('--render-quality',(f.quality||1).toFixed(2));body.classList.toggle('perf-low',(f.quality||1)<.82);$('#lens-status').textContent=`LOCAL 3D // ${Math.round(f.fps||60)} FPS // Q${Math.round((f.quality||1)*100)}`;if(!mapOverlay.hidden)$('#map-readout').textContent=`${(Math.sin(f.time*.21)*47.2).toFixed(3)} // ${(Math.cos(f.time*.17)*88.4).toFixed(3)}`;};current=routeFromHash();if(!engine.scenes[current])current='home';setPalette(current);renderLens(current);engine.setRoute(current,true);$('#engine-error').hidden=true;}catch(e){console.error(e);$('#engine-error').hidden=false;$('#engine-error').innerHTML=`<b>LOCAL WEBGL2 ENGINE COULD NOT START</b><span>${esc(e.message)}</span><a href="DIAGNOSTICS.html">OPEN DIAGNOSTICS →</a>`;$('#lens-status').textContent='WEBGL2 ERROR';}
  if(window.__AETER_BOOT_INTENT__!==undefined){const v=window.__AETER_BOOT_INTENT__;delete window.__AETER_BOOT_INTENT__;enter(v);}
}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
