(function(){
'use strict';
const D=window.AETER_DATA;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#world'), boot=$('#boot'), app=$('#app'), lens=$('#lens'), content=$('#lens-content'), routeIndex=$('#route-index'), routeLabel=$('#route-label'), hoverHint=$('#hover-hint');
const atlas=$('#atlas'), atlasLabels=$('#atlas-labels'), signal=$('#signal'), signalInput=$('#signal-input'), signalResults=$('#signal-results'), signalStatus=$('#signal-status');
const audio=$('#ost'), volume=$('#volume'), mute=$('#mute'), spectrum=$('#spectrum'), sc=spectrum.getContext('2d');
let engine=null, current='home', returnRoute='home', soundStarted=false, muted=false, audioCtx=null, source=null, filter=null, analyser=null, master=null, freqData=null, searchItems=[], selectedSearch=0, atlasNodes=new Map(), focusMode=false;
const labels={home:['00','ORIGIN'],projects:['01','PROJECT ARCHIVE'],cyber:['02','BREACH LAB'],about:['03','IDENTITY ORBIT'],contact:['04','UPLINK']};
const routeName=r=>{if(r.startsWith('project:')){const p=D.projects.find(x=>'project:'+x.slug===r);return p?p.name:'PROJECT'}return ({home:'ORIGIN',projects:'PROJECT ARCHIVE',cyber:'BREACH LAB',about:'IDENTITY ORBIT',contact:'UPLINK',atlas:'NEXUS',search:'SIGNAL FIELD'})[r]||r.toUpperCase()};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function projectByRoute(r){return D.projects.find(p=>'project:'+p.slug===r)}
function setTheme(route){const p=engine?.presets?.[route]||engine?.presets?.home;if(!p)return;document.documentElement.style.setProperty('--accent',p.colors[0]);document.documentElement.style.setProperty('--accent2',p.colors[1]);document.documentElement.style.setProperty('--cream',p.colors[2]);}
function btn(text,route,primary=false){return `<button class="btn${primary?' primary':''}" data-route="${route}">${text} <span>↗</span></button>`}
function linkBtn(text,href,primary=false){return `<a class="btn${primary?' primary':''}" href="${href}" target="_blank" rel="noreferrer">${text} <span>↗</span></a>`}
function renderHome(){return `<div class="kicker">0xAeterNova / Spatial Portfolio</div><h1 class="display">BUILD.<br/><span class="outline">BREAK.</span> EVOLVE.</h1><p class="lede">${esc(D.profile.intro)}</p><div class="triad"><div><small>BUILD</small><strong>Robotics / Embedded</strong></div><div><small>THINK</small><strong>AI / Vision</strong></div><div><small>BREAK</small><strong>REV / PWN / CTF</strong></div></div><div class="actions">${btn('OPEN PROJECT ARCHIVE','projects',true)}${linkBtn('GITHUB',D.profile.links.github)}</div>`}
function renderProjects(){return `<div class="kicker">Selected Work / Living Archive</div><h1 class="display">PROJECT<br/><span class="outline">CONSTELLATION.</span></h1><p class="lede">Every project is a different physical system inside the same portfolio field. Select one in 3D or from the index below.</p><div class="archive-list">${D.projects.map(p=>`<div class="archive-item" data-route="project:${p.slug}"><span class="num">${p.index}</span><div><strong>${esc(p.name)}</strong><p>${esc(p.tagline)}</p></div><span class="arrow">↗</span></div>`).join('')}</div>`}
function renderProject(p){return `<div class="kicker">${esc(p.index)} / ${esc(p.realm)} / ${esc(p.status)}</div><h1 class="display">${esc(p.name).replace(' ','<br/>')}</h1><img class="project-preview" src="assets/projects/${p.slug}.svg" alt="${esc(p.name)} project artwork"/><p class="lede">${esc(p.tagline)}</p><p class="copy">${esc(p.description)}</p><div class="project-metrics"><div><small>STATUS</small><b>${esc(p.status)}</b></div><div><small>YEAR</small><b>${esc(p.year)}</b></div></div><div class="tag-row">${p.stack.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><p class="copy"><b>My contribution:</b> ${esc(p.contribution)}</p><div class="actions">${linkBtn('VIEW REPOSITORY',p.repo,true)}${btn('BACK TO ARCHIVE','projects')}</div>`}
function renderCyber(){return `<div class="kicker">Security / GeomRavage / CTF</div><h1 class="display">BREAK<br/><span class="outline">THE MODEL.</span></h1><p class="lede">Security is part of how I understand systems — especially where binaries, memory, protocols and assumptions meet.</p><div class="tag-row">${D.profile.ctfFocus.map(x=>`<span class="tag">${x}</span>`).join('')}</div><div style="margin-top:24px">${D.achievements.map(a=>`<a class="achievement" href="${a.href}" target="_blank" rel="noreferrer"><span><b>${esc(a.title)}</b><br/><small>${esc(a.detail)}</small></span><span>↗</span></a>`).join('')}</div><img class="project-preview" src="assets/profile/trophy-1.png" alt="Achievement trophy" style="object-fit:contain;background:rgba(0,0,0,.22)"/><div class="actions">${linkBtn('CTFTIME',D.profile.links.ctftime,true)}${linkBtn('GEOMRAVAGE',D.profile.links.team)}</div>`}
function renderAbout(){return `<div class="kicker">Identity / Robotics × AI × Security</div><h1 class="display">ZAID<br/><span class="outline">TAWALBEH.</span></h1><div class="identity-grid"><div class="identity-art"><img src="assets/profile/profile-hero-dark.svg" alt="Original 0xAeterNova GitHub profile hero"/></div><div><p class="lede">${esc(D.profile.about[0])}</p><p class="copy">${esc(D.profile.about[1])}</p><div class="skill-matrix">${D.skills.map(s=>`<div class="skill-cluster"><b>${esc(s.group)}</b><p>${s.items.map(esc).join(' · ')}</p></div>`).join('')}</div></div></div><img class="heatmap" src="assets/profile/heatmap-dark.svg" alt="GitHub contribution heatmap"/><div class="actions">${linkBtn('LINKEDIN',D.profile.links.linkedin,true)}${linkBtn('GITHUB',D.profile.links.github)}${linkBtn('CTFTIME',D.profile.links.ctftime)}</div>`}
function renderContact(){const links=[['GITHUB',D.profile.links.github,'CODE / PROJECTS'],['LINKEDIN',D.profile.links.linkedin,'PROFESSIONAL'],['CTFTIME',D.profile.links.ctftime,'CTF PROFILE'],['LINKTREE',D.profile.links.linktree,'ALL SIGNALS'],['INSTAGRAM',D.profile.links.instagram,'SOCIAL'],['TELEGRAM',D.profile.links.telegram,'DIRECT']];return `<div class="kicker">Uplink / Collaboration</div><h1 class="display">SEND A<br/><span class="outline">SIGNAL.</span></h1><p class="lede">Projects, research, CTFs, robotics, AI, embedded systems or strange technical ideas — choose a channel.</p><div class="contact-grid">${links.map(x=>`<a class="contact-card" href="${x[1]}" target="_blank" rel="noreferrer"><small>${x[2]}</small><b>${x[0]} ↗</b></a>`).join('')}</div>`}
function renderLens(route){const p=projectByRoute(route);let html='';if(route==='home')html=renderHome();else if(route==='projects')html=renderProjects();else if(route==='cyber')html=renderCyber();else if(route==='about')html=renderAbout();else if(route==='contact')html=renderContact();else if(p)html=renderProject(p);content.innerHTML=html;const base=p?[p.index,p.realm]:labels[route]||['--',routeName(route)];routeIndex.textContent=base[0];routeLabel.textContent=base[1];const side=route==='projects'||route==='about'?'right':route==='contact'?'center':'left';lens.classList.remove('lens-left','lens-right','lens-center');lens.classList.add('lens-'+side);$$('#route-rail button').forEach(b=>{const r=b.dataset.route;b.classList.toggle('active',route===r||(route.startsWith('project:')&&r==='projects'))});$('#field-readout').textContent='FIELD / '+routeName(route).toUpperCase();}
function transitionAudio(){if(!audioCtx||!filter)return;const t=audioCtx.currentTime;filter.frequency.cancelScheduledValues(t);filter.frequency.setValueAtTime(filter.frequency.value,t);filter.frequency.exponentialRampToValueAtTime(620,t+.18);filter.frequency.exponentialRampToValueAtTime(13500,t+1.1)}
function navigate(route,{hash=true}={}){if(!engine||!engine.scenes[route])return;closeOverlays(false);if(route===current)return;lens.classList.add('is-away');transitionAudio();setTimeout(()=>{current=route;engine.setRoute(route);setTheme(route);renderLens(route);if(hash)history.replaceState(null,'','#'+(route.startsWith('project:')?'project/'+route.split(':')[1]:route));requestAnimationFrame(()=>lens.classList.remove('is-away'))},260)}
function openAtlas(){if(!engine)return;returnRoute=current;atlas.hidden=false;app.classList.add('is-hidden');engine.setRoute('atlas');setTheme('atlas');buildAtlasLabels()}
function closeAtlas(goBack=true){atlas.hidden=true;atlasLabels.innerHTML='';atlasNodes.clear();app.classList.remove('is-hidden');if(goBack&&engine){engine.setRoute(returnRoute);setTheme(returnRoute)}}
function buildAtlasLabels(){atlasLabels.innerHTML='';const routes=['home','projects','cyber','about','contact',...D.projects.map(p=>'project:'+p.slug)];routes.forEach(r=>{const b=document.createElement('button');b.className='atlas-node';b.dataset.route=r;b.innerHTML=`${esc(routeName(r))}<small>${r.startsWith('project:')?'PROJECT REALM':'CORE REALM'}</small>`;atlasLabels.appendChild(b);atlasNodes.set(r,b)})}
function updateAtlas(anchors){if(atlas.hidden)return;anchors.forEach(a=>{const el=atlasNodes.get(a.route);if(!el)return;el.style.left=a.pos.x+'px';el.style.top=a.pos.y+'px';el.style.opacity=a.pos.visible?'1':'0';el.style.pointerEvents=a.pos.visible?'auto':'none'})}
function renderSearch(){const q=signalInput.value;searchItems=engine.search(q);engine.setSearchResults?.(searchItems);selectedSearch=clampIndex(selectedSearch,searchItems.length);signalStatus.textContent=searchItems.length?`${searchItems.length} SIGNAL${searchItems.length===1?'':'S'} LOCKED · ↑/↓ TO TUNE · ENTER TO TRAVEL`:'NO MATCH · TRY ANOTHER SIGNAL';signalResults.innerHTML=searchItems.slice(0,3).map((x,i)=>`<div class="signal-card${i===selectedSearch?' active':''}" data-result="${i}"><small>${x.route.startsWith('project:')?'PROJECT':'REALM'} / ${String(i+1).padStart(2,'0')}</small><b>${esc(x.label)}</b><span>${esc(x.keywords.split(' ').slice(0,8).join(' · '))}</span><span class="go">↗</span></div>`).join('')}
function clampIndex(i,n){return n?((i%n)+n)%n:0}
function openSearch(){if(!engine)return;returnRoute=current;signal.hidden=false;app.classList.add('is-hidden');engine.setRoute('search');setTheme('search');signalInput.value='';selectedSearch=0;renderSearch();setTimeout(()=>signalInput.focus(),60)}
function closeSearch(goBack=true){signal.hidden=true;app.classList.remove('is-hidden');if(goBack&&engine){engine.setRoute(returnRoute);setTheme(returnRoute)}}
function closeOverlays(restore=false){if(!atlas.hidden)closeAtlas(restore);if(!signal.hidden)closeSearch(restore)}
function commitSearch(index=selectedSearch){const hit=searchItems[index];if(!hit)return;signal.hidden=true;app.classList.remove('is-hidden');current=returnRoute;engine.setRoute(returnRoute,true);navigate(hit.route)}
async function startSound(){try{if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();source=audioCtx.createMediaElementSource(audio);filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=13500;const comp=audioCtx.createDynamicsCompressor();comp.threshold.value=-16;comp.knee.value=14;comp.ratio.value=3;comp.attack.value=.005;comp.release.value=.24;analyser=audioCtx.createAnalyser();analyser.fftSize=256;analyser.smoothingTimeConstant=.78;master=audioCtx.createGain();master.gain.value=parseFloat(volume.value);source.connect(filter);filter.connect(comp);comp.connect(analyser);analyser.connect(master);master.connect(audioCtx.destination);freqData=new Uint8Array(analyser.frequencyBinCount)}if(audioCtx.state==='suspended')await audioCtx.resume();audio.volume=1;await audio.play();soundStarted=true;muted=false;mute.textContent='♪'}catch(e){console.warn('Audio start failed',e);}}
function setVolume(v){if(master&&audioCtx)master.gain.setTargetAtTime(v,audioCtx.currentTime,.03);else audio.volume=v}
function toggleMute(){if(!soundStarted){startSound();return}muted=!muted;if(master&&audioCtx)master.gain.setTargetAtTime(muted?0:parseFloat(volume.value),audioCtx.currentTime,.04);else audio.muted=muted;mute.textContent=muted?'×':'♪'}
function audioFrame(){if(!analyser||!freqData){sc.clearRect(0,0,spectrum.width,spectrum.height);return 0}analyser.getByteFrequencyData(freqData);let sum=0;sc.clearRect(0,0,84,24);for(let i=0;i<21;i++){const v=freqData[i*3]/255;sum+=v;sc.fillStyle=`rgba(255,${110+Math.floor(v*120)},${90+Math.floor(v*130)},${.28+v*.72})`;sc.fillRect(i*4,24-v*22,2.4,v*22)}return sum/21}
function enter(withSound){if(withSound)startSound();boot.classList.add('is-leaving');app.classList.remove('is-hidden');setTimeout(()=>boot.hidden=true,1250)}
function parseHash(){const h=location.hash.replace(/^#/,'');if(h.startsWith('project/'))return 'project:'+h.slice(8);return h||'home'}
function init(){try{engine=new window.AeterEngine(canvas);engine.onNavigate=r=>navigate(r);engine.onHover=r=>{if(r){hoverHint.textContent='OPEN / '+routeName(r);hoverHint.classList.add('show')}else hoverHint.classList.remove('show')};engine.onFrame=f=>{updateAtlas(f.atlas);const lvl=audioFrame();engine.setAudioLevel(lvl)};current=parseHash();if(!engine.scenes[current])current='home';engine.setRoute(current,true);setTheme(current);renderLens(current)}catch(e){console.error(e);const box=$('#engine-error');box.hidden=false;box.textContent='WEBGL ENGINE ERROR — '+e.message+' · Try Chrome/Edge with hardware acceleration enabled.';boot.querySelector('.boot-lede').textContent='The local 3D engine could not start in this browser. Hardware acceleration / WebGL2 may be disabled.'}
 $('#enter-sound').addEventListener('click',()=>enter(true));$('#enter-silent').addEventListener('click',()=>enter(false));$('#atlas-open').addEventListener('click',openAtlas);$('#search-open').addEventListener('click',openSearch);$('#mute').addEventListener('click',toggleMute);volume.addEventListener('input',e=>{setVolume(parseFloat(e.target.value));if(muted)toggleMute()});
 document.addEventListener('click',e=>{const route=e.target.closest('[data-route]')?.dataset.route;if(route){if(!atlas.hidden){closeAtlas(false);current=returnRoute;engine.setRoute(returnRoute,true)}navigate(route);return}const c=e.target.closest('[data-close]')?.dataset.close;if(c==='atlas')closeAtlas(true);if(c==='signal')closeSearch(true);const idx=e.target.closest('[data-result]')?.dataset.result;if(idx!=null)commitSearch(parseInt(idx,10))});
 signalInput.addEventListener('input',()=>{selectedSearch=0;renderSearch()});
 addEventListener('keydown',e=>{if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&signal.hidden){e.preventDefault();openSearch();return}if(e.key==='Escape'){if(!signal.hidden)closeSearch(true);else if(!atlas.hidden)closeAtlas(true);return}if(!signal.hidden){if(e.key==='ArrowDown'||e.key==='ArrowRight'){e.preventDefault();selectedSearch=clampIndex(selectedSearch+1,Math.min(3,searchItems.length));renderSearch()}if(e.key==='ArrowUp'||e.key==='ArrowLeft'){e.preventDefault();selectedSearch=clampIndex(selectedSearch-1,Math.min(3,searchItems.length));renderSearch()}if(e.key==='Enter'){e.preventDefault();commitSearch()};return}if(e.key.toLowerCase()==='m'){e.preventDefault();openAtlas()}if(e.key.toLowerCase()==='f'){focusMode=!focusMode;app.style.opacity=focusMode?'0':'1';app.style.pointerEvents=focusMode?'none':''}if(e.key==='1')navigate('home');if(e.key==='2')navigate('projects');if(e.key==='3')navigate('cyber');if(e.key==='4')navigate('about');if(e.key==='5')navigate('contact')});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
