const scales={
  home:[55,82.41,110,164.81], projects:[65.41,98,130.81,196], cyber:[46.25,69.3,92.5,138.59], about:[73.42,110,146.83,220], contact:[61.74,92.5,123.47,185],
  ruvigil:[58.27,87.31,116.54,174.61], phantom:[69.3,103.83,138.59,207.65], elif:[49,73.42,98,146.83]
};
const realmKey=route=>route.startsWith('project/')?(route.includes('ruvigil')?'ruvigil':route.includes('phantom')?'phantom':route.includes('elif-linux')?'elif':'projects'):route;

export class SpatialAudio{
  constructor(){this.ctx=null;this.enabled=false;this.route='home';this.volume=.48;this.nodes=[];this.loopTimer=null;this.pulseTimer=null;this.master=null;this.comp=null;this.analyser=null;this.delay=null;this.delayGain=null;this.noiseBuffer=null;this.wave=null;}
  async init(){
    if(this.ctx)return;this.ctx=new (window.AudioContext||window.webkitAudioContext)();
    this.master=this.ctx.createGain();this.master.gain.value=0;
    this.comp=this.ctx.createDynamicsCompressor();this.comp.threshold.value=-24;this.comp.knee.value=18;this.comp.ratio.value=3;this.comp.attack.value=.008;this.comp.release.value=.28;this.analyser=this.ctx.createAnalyser();this.analyser.fftSize=256;this.wave=new Uint8Array(this.analyser.fftSize);
    this.delay=this.ctx.createDelay(1.2);this.delay.delayTime.value=.34;this.delayGain=this.ctx.createGain();this.delayGain.gain.value=.24;this.delay.connect(this.delayGain);this.delayGain.connect(this.delay);this.delayGain.connect(this.comp);
    this.master.connect(this.comp);this.comp.connect(this.analyser);this.analyser.connect(this.ctx.destination);
    const len=this.ctx.sampleRate*2,b=this.ctx.createBuffer(1,len,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*(1-i/len*.15);this.noiseBuffer=b;
  }
  async start(on=true){await this.init();await this.ctx.resume();this.enabled=on;this.master.gain.cancelScheduledValues(this.ctx.currentTime);this.master.gain.linearRampToValueAtTime(on?this.volume:0,this.ctx.currentTime+.45);if(on){this.rebuild();this.startRhythm();this.transition('home');}return this.enabled;}
  async toggle(){await this.init();await this.ctx.resume();this.enabled=!this.enabled;this.master.gain.cancelScheduledValues(this.ctx.currentTime);this.master.gain.linearRampToValueAtTime(this.enabled?this.volume:0,this.ctx.currentTime+.32);if(this.enabled){this.rebuild();this.startRhythm();this.uiTick(1.1)}else this.stopRhythm();return this.enabled;}
  setVolume(v){this.volume=Math.max(0,Math.min(1,v));if(this.master&&this.enabled)this.master.gain.setTargetAtTime(this.volume,this.ctx.currentTime,.08);}
  setRoute(route){this.route=route;if(this.enabled){this.transition(route);setTimeout(()=>this.rebuild(),180);}}
  clearVoices(){if(!this.ctx)return;const now=this.ctx.currentTime;this.nodes.forEach(n=>{try{if(n.gain)n.gain.gain.setTargetAtTime(0,now,.15);if(n.stop)n.stop(now+.55);else if(n.osc)n.osc.stop(now+.55);}catch{}});this.nodes=[];}
  rebuild(){
    if(!this.ctx||!this.enabled)return;this.clearVoices();const key=realmKey(this.route),fs=scales[key]||scales.home,now=this.ctx.currentTime;
    fs.slice(0,3).forEach((f,i)=>{const osc=this.ctx.createOscillator(),g=this.ctx.createGain(),filter=this.ctx.createBiquadFilter(),pan=this.ctx.createStereoPanner();osc.type=i===0?'sine':i===1?'triangle':'sawtooth';osc.frequency.value=f;osc.detune.value=(i-1)*5;filter.type='lowpass';filter.frequency.value=key==='cyber'?760:460+i*260;filter.Q.value=1.1;g.gain.value=0;pan.pan.value=(i-1)*.42;osc.connect(filter);filter.connect(g);g.connect(pan);pan.connect(this.master);pan.connect(this.delay);osc.start();g.gain.linearRampToValueAtTime(i===0?.17:i===1?.075:.04,now+1.4+i*.25);this.nodes.push({osc,gain:g,stop:t=>osc.stop(t)});});
    const sub=this.ctx.createOscillator(),sg=this.ctx.createGain(),sf=this.ctx.createBiquadFilter();sub.type='sine';sub.frequency.value=fs[0]/2;sf.type='lowpass';sf.frequency.value=130;sg.gain.value=0;sub.connect(sf);sf.connect(sg);sg.connect(this.master);sub.start();sg.gain.linearRampToValueAtTime(key==='cyber'?.11:.075,now+1.8);this.nodes.push({osc:sub,gain:sg,stop:t=>sub.stop(t)});
    const noise=this.ctx.createBufferSource(),ng=this.ctx.createGain(),nf=this.ctx.createBiquadFilter(),np=this.ctx.createStereoPanner();noise.buffer=this.noiseBuffer;noise.loop=true;nf.type=key==='ruvigil'?'bandpass':'lowpass';nf.frequency.value=key==='ruvigil'?1100:520;nf.Q.value=key==='ruvigil'?4:.6;ng.gain.value=0;np.pan.value=.2;noise.connect(nf);nf.connect(ng);ng.connect(np);np.connect(this.master);noise.start();ng.gain.linearRampToValueAtTime(key==='cyber'?.035:.018,now+1.6);this.nodes.push({gain:ng,stop:t=>noise.stop(t)});
    const lfo=this.ctx.createOscillator(),lg=this.ctx.createGain();lfo.frequency.value=key==='phantom'?.17:.08;lg.gain.value=key==='phantom'?160:80;lfo.connect(lg);lg.connect(sf.frequency);lfo.start();this.nodes.push({stop:t=>lfo.stop(t)});
  }
  startRhythm(){this.stopRhythm();const fire=()=>{if(!this.enabled)return;const key=realmKey(this.route);if(key==='cyber')this.hit(.8,70+Math.random()*55);else if(key==='ruvigil')this.ping(900+Math.random()*500);else if(key==='phantom')this.spark(420+Math.random()*400);else if(Math.random()>.4)this.spark(250+Math.random()*280);const wait=key==='cyber'?520+Math.random()*420:key==='ruvigil'?1050+Math.random()*650:1500+Math.random()*1300;this.pulseTimer=setTimeout(fire,wait);};fire();}
  stopRhythm(){clearTimeout(this.pulseTimer);this.pulseTimer=null;}
  envelope(node,gain,peak,attack,release){const t=this.ctx.currentTime;gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,peak),t+attack);gain.gain.exponentialRampToValueAtTime(.0001,t+attack+release);try{node.start(t);node.stop(t+attack+release+.03);}catch{}}
  hit(level=.7,f=82){if(!this.enabled||!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.setValueAtTime(f,this.ctx.currentTime);o.frequency.exponentialRampToValueAtTime(f*.45,this.ctx.currentTime+.3);o.connect(g);g.connect(this.master);this.envelope(o,g,.11*level,.008,.42);}
  ping(f=1200){if(!this.enabled||!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),p=this.ctx.createStereoPanner();o.type='sine';o.frequency.value=f;p.pan.value=Math.random()*1.6-.8;o.connect(g);g.connect(p);p.connect(this.master);p.connect(this.delay);this.envelope(o,g,.035,.008,.42);}
  spark(f=440){if(!this.enabled||!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),p=this.ctx.createStereoPanner();o.type='triangle';o.frequency.value=f;o.detune.value=Math.random()*18-9;p.pan.value=Math.random()*1.4-.7;o.connect(g);g.connect(p);p.connect(this.master);p.connect(this.delay);this.envelope(o,g,.024,.02,.65);}
  uiTick(power=.6){if(!this.enabled||!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='square';o.frequency.setValueAtTime(760,this.ctx.currentTime);o.frequency.exponentialRampToValueAtTime(280,this.ctx.currentTime+.07);o.connect(g);g.connect(this.master);this.envelope(o,g,.018*power,.003,.075);}
  getLevel(){if(!this.analyser||!this.enabled)return 0;this.analyser.getByteTimeDomainData(this.wave);let sum=0;for(let i=0;i<this.wave.length;i++){const v=(this.wave[i]-128)/128;sum+=v*v;}return Math.min(1,Math.sqrt(sum/this.wave.length)*4.2);}
  transition(route){if(!this.enabled||!this.ctx)return;const t=this.ctx.currentTime;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();o.type='sawtooth';o.frequency.setValueAtTime(92,t);o.frequency.exponentialRampToValueAtTime(680,t+.75);f.type='bandpass';f.frequency.setValueAtTime(260,t);f.frequency.exponentialRampToValueAtTime(1800,t+.75);f.Q.value=2;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.065,t+.14);g.gain.exponentialRampToValueAtTime(.0001,t+.9);o.connect(f);f.connect(g);g.connect(this.master);g.connect(this.delay);o.start(t);o.stop(t+.92);setTimeout(()=>this.hit(.95,(scales[realmKey(route)]||scales.home)[0]*1.5),650);}
}
