import { projects, skills } from './data.js';

const TAU = Math.PI * 2;
const clamp = (v,a,b)=>Math.max(a,Math.min(b,v));
const lerp = (a,b,t)=>a+(b-a)*t;
const smooth = t=>t*t*(3-2*t);
const ease = t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
const hex = h=>{h=h.replace('#',''); if(h.length===3) h=[...h].map(x=>x+x).join(''); return [parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255];};
const norm=a=>{const l=Math.hypot(...a)||1;return a.map(v=>v/l)};
const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
function m4(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);}
function mm(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
function persp(fov,aspect,n,f){const t=1/Math.tan(fov/2),o=new Float32Array(16);o[0]=t/aspect;o[5]=t;o[10]=(f+n)/(n-f);o[11]=-1;o[14]=2*f*n/(n-f);return o;}
function look(eye,target,up=[0,1,0]){const z=norm(sub(eye,target)),x=norm(cross(up,z)),y=cross(z,x),o=m4();o[0]=x[0];o[1]=y[0];o[2]=z[0];o[4]=x[1];o[5]=y[1];o[6]=z[1];o[8]=x[2];o[9]=y[2];o[10]=z[2];o[12]=-(x[0]*eye[0]+x[1]*eye[1]+x[2]*eye[2]);o[13]=-(y[0]*eye[0]+y[1]*eye[1]+y[2]*eye[2]);o[14]=-(z[0]*eye[0]+z[1]*eye[1]+z[2]*eye[2]);return o;}
function trs(p,r,s){let o=m4();const cx=Math.cos(r[0]),sx=Math.sin(r[0]),cy=Math.cos(r[1]),sy=Math.sin(r[1]),cz=Math.cos(r[2]),sz=Math.sin(r[2]);const rx=new Float32Array([1,0,0,0,0,cx,sx,0,0,-sx,cx,0,0,0,0,1]);const ry=new Float32Array([cy,0,-sy,0,0,1,0,0,sy,0,cy,0,0,0,0,1]);const rz=new Float32Array([cz,sz,0,0,-sz,cz,0,0,0,1,0,0,0,0,1]);const sc=new Float32Array([s[0],0,0,0,0,s[1],0,0,0,0,s[2],0,0,0,0,1]);o=mm(o,rx);o=mm(o,ry);o=mm(o,rz);o=mm(o,sc);o[12]=p[0];o[13]=p[1];o[14]=p[2];return o;}
function projectPoint(m,p){const x=p[0],y=p[1],z=p[2],w=m[3]*x+m[7]*y+m[11]*z+m[15];return [(m[0]*x+m[4]*y+m[8]*z+m[12])/w,(m[1]*x+m[5]*y+m[9]*z+m[13])/w,(m[2]*x+m[6]*y+m[10]*z+m[14])/w,w];}
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||'Shader compile failed');return s;}
function program(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'Program link failed');return p;}
function cube(){const p=[-1,-1,1,1,-1,1,1,1,1,-1,1,1,1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1,-1,1,1,1,1,1,1,1,-1,-1,1,-1,-1,-1,-1,-1,1,-1,1,1,1,-1,1,-1,1,-1,1,1,-1,1,1,-1,-1,-1,-1,1,-1,-1,1,-1,1,-1,1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1,1,1,-1];const n=[0,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,1,0,0,1,0,0,1,0,0,1,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0];const i=[];for(let f=0;f<6;f++){const a=f*4;i.push(a,a+1,a+2,a,a+2,a+3)}return {p,n,i};}
function sphere(lat=18,lon=28){const p=[],n=[],i=[];for(let y=0;y<=lat;y++){const v=y/lat,ph=v*Math.PI;for(let x=0;x<=lon;x++){const u=x/lon,th=u*TAU,s=Math.sin(ph),px=Math.cos(th)*s,py=Math.cos(ph),pz=Math.sin(th)*s;p.push(px,py,pz);n.push(px,py,pz)}}for(let y=0;y<lat;y++)for(let x=0;x<lon;x++){const a=y*(lon+1)+x,b=a+lon+1;i.push(a,b,a+1,b,b+1,a+1)}return {p,n,i};}
function torus(R=1,r=.026,seg=64,tube=10){const p=[],n=[],i=[];for(let j=0;j<=tube;j++){const v=j/tube*TAU,cv=Math.cos(v),sv=Math.sin(v);for(let k=0;k<=seg;k++){const u=k/seg*TAU,cu=Math.cos(u),su=Math.sin(u);p.push((R+r*cv)*cu,r*sv,(R+r*cv)*su);n.push(cv*cu,sv,cv*su)}}for(let j=0;j<tube;j++)for(let k=0;k<seg;k++){const a=j*(seg+1)+k,b=a+seg+1;i.push(a,b,a+1,b,b+1,a+1)}return {p,n,i};}
function cylinder(seg=28){const p=[],n=[],i=[];for(let y=0;y<2;y++){const yy=y?1:-1;for(let k=0;k<=seg;k++){const a=k/seg*TAU,c=Math.cos(a),s=Math.sin(a);p.push(c,yy,s);n.push(c,0,s)}}for(let k=0;k<seg;k++){const a=k,b=k+seg+1;i.push(a,b,a+1,b,b+1,a+1)}return {p,n,i};}
function octa(){return {p:[1,0,0,-1,0,0,0,1,0,0,-1,0,0,0,1,0,0,-1],n:[1,0,0,-1,0,0,0,1,0,0,-1,0,0,0,1,0,0,-1],i:[0,2,4,4,2,1,1,2,5,5,2,0,0,4,3,4,1,3,1,5,3,5,0,3]};}
function line(points){const p=[],n=[];points.forEach(q=>{p.push(...q);n.push(0,1,0)});return {p,n,line:true};}

export class TransmissionMachine {
  constructor(canvas){
    this.canvas=canvas;this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!this.gl)throw new Error('WebGL2 unavailable. Enable hardware acceleration in Chrome/Edge.');
    this.route='home';this.prevRoute=null;this.transition=1;this.transitionStart=0;this.transitionDuration=1450;this.time=0;this.last=performance.now();this.pointer=[0,0];this.pointerSmooth=[0,0];this.drag=false;this.dragMoved=false;this.yaw=0;this.pitch=0;this.zoom=1;this.audio=0;this.exploded=false;this.explodeTarget=0;this.explodeAmount=0;this.mapFocus=null;this.searchFocus=0;this.hover=null;this.onNavigate=null;this.onHover=null;this.onFrame=null;this.interactives=[];this.mapAnchors=[];this.searchNodes=[];this.uniformCache=new WeakMap();this.fpsAcc=0;this.fpsFrames=0;this.fps=60;this.qualityScale=1;this.particleRatio=1;this.bloomPasses=4;this.lastQualityChange=0;this.dprCap=(navigator.hardwareConcurrency||8)<=4?1.28:((navigator.deviceMemory||8)<=4?1.35:1.62);
    this.palette={a:hex('#ff744f'),b:hex('#8159ff'),c:hex('#fff0ad')};this.paletteFrom={a:[...this.palette.a],b:[...this.palette.b],c:[...this.palette.c]};this.paletteTo={a:[...this.palette.a],b:[...this.palette.b],c:[...this.palette.c]};
    this.presets={
      home:{cam:[16,7,28],target:[0,0,0],colors:['#ff744f','#8159ff','#fff0ad'],exposure:.92,bloom:.86},
      projects:{cam:[15,5,30],target:[0,0,0],colors:['#ff2ea6','#19e6ff','#fff4cb'],exposure:.86,bloom:.96},
      'project/ruvigil':{cam:[17,7,28],target:[0,1,0],colors:['#47f5ff','#c67a24','#e7fff9'],exposure:.84,bloom:.92},
      'project/phantom':{cam:[15,6,27],target:[0,0,0],colors:['#ff5bd7','#6d44ff','#dffff4'],exposure:.82,bloom:1.0},
      'project/elif-linux':{cam:[17,7,29],target:[0,0,0],colors:['#b9ff43','#ff5038','#eef9ce'],exposure:.78,bloom:.82},
      cyber:{cam:[18,7,30],target:[0,0,0],colors:['#faff00','#ff5a1f','#f3ffc0'],exposure:.76,bloom:.78},
      about:{cam:[15,8,30],target:[0,0,0],colors:['#ffd87a','#7d52ff','#a9ffe6'],exposure:.86,bloom:.86},
      contact:{cam:[0,7,30],target:[0,0,0],colors:['#88ffd5','#ff9b78','#e6e0ff'],exposure:.86,bloom:.92},
      map:{cam:[0,5,37],target:[0,1,0],colors:['#6ce8ff','#ff5d98','#fff0ae'],exposure:.82,bloom:.95},
      search:{cam:[0,2,31],target:[0,0,0],colors:['#ffffff','#ff5d98','#6ce8ff'],exposure:.83,bloom:.88}
    };
    this.setupPrograms();this.setupGeometry();this.setupTargets();this.buildScenes();this.resize();this.bind();this.setRoute('home',true);this.loop=this.loop.bind(this);requestAnimationFrame(this.loop);
  }
  U(p,n){let m=this.uniformCache.get(p);if(!m){m=new Map();this.uniformCache.set(p,m)}if(!m.has(n))m.set(n,this.gl.getUniformLocation(p,n));return m.get(n);}
  setupPrograms(){const gl=this.gl;
    this.meshP=program(gl,`#version 300 es\nprecision highp float;layout(location=0)in vec3 aP;layout(location=1)in vec3 aN;uniform mat4 uM,uVP;out vec3 vN;out vec3 vW;void main(){vec4 w=uM*vec4(aP,1.);vW=w.xyz;vN=normalize(mat3(uM)*aN);gl_Position=uVP*w;}`,`#version 300 es\nprecision highp float;in vec3 vN;in vec3 vW;uniform vec3 uC,uA;uniform float uE,uAlpha,uT,uAudio;out vec4 o;void main(){vec3 n=normalize(vN);vec3 l1=normalize(vec3(.35,.82,.55));vec3 l2=normalize(vec3(-.72,.18,-.5));float d=max(0.,dot(n,l1))*.74+max(0.,dot(n,l2))*.24;float rim=pow(1.-abs(dot(n,normalize(-vW))),2.25);float pulse=.5+.5*sin(uT*2.+vW.y*1.7+vW.x*.45);vec3 c=uC*(.13+d*.82)+uA*(rim*(.32+uE*.58))+uC*uE*(.12+.10*pulse+.12*uAudio);o=vec4(c,uAlpha);}`);    this.bgP=program(gl,`#version 300 es\nout vec2 v;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);v=p;gl_Position=vec4(p*2.-1.,0,1);}`,`#version 300 es\nprecision highp float;in vec2 v;uniform float uT,uWarp,uAudio,uMode;uniform vec3 uA,uB,uC;uniform vec2 uP;out vec4 o;float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+vec2(1,1)),f.x),f.y);}float fbm(vec2 p){float s=0.,a=.5;for(int i=0;i<5;i++){s+=a*n(p);p=mat2(1.7,1.2,-1.2,1.7)*p;a*=.5;}return s;}void main(){vec2 uv=v-.5;float r=length(uv);float ang=atan(uv.y,uv.x);float f=fbm(v*3.2+vec2(uT*.018,-uT*.012)+uP*.09);vec3 c=mix(uB*.052,uA*.095+.006,f);float neb=pow(max(0.,fbm(v*5.5+uT*.008)-.48),2.)*1.8;c+=mix(uA,uB,f)*neb*.06;float aur=exp(-abs(uv.y-(sin(uv.x*5.+uT*.19+uMode)*.055+.13))*22.)*(.5+.5*sin(uv.x*13.-uT*.31));c+=mix(uA,uC,.45+uv.x)*aur*(.035+.035*uAudio);float lane=pow(max(0.,sin((uv.x*.88+uv.y*.32)*118.-uT*(1.2+uMode*.07))),24.)*smoothstep(.58,.08,r);c+=uC*lane*(.014+.022*uAudio);float fil=pow(max(0.,sin(ang*(7.+mod(uMode,4.))-uT*.16+f*5.)),20.)*(1.-smoothstep(.12,.74,r));c+=uC*fil*.035;float gx=abs(fract((uv.x/(max(.035,uv.y+.58)))*14.)-.5);float grid=step(.487,gx)*smoothstep(-.02,-.46,uv.y)*.15;c+=mix(uB,uA,.5)*grid*.06;float cell=floor(v.x*72.);float bh=.022+h(vec2(cell,11.+floor(uMode)))*.095;float skyline=step(v.y,bh)*(1.-step(v.y,bh*.17));c+=mix(uB,uA,h(vec2(cell,9.)))*skyline*.12;float beacon=step(.985,h(vec2(cell,31.)))*exp(-abs(v.y-bh)*130.);c+=uC*beacon*.24;float tunnel=exp(-abs(fract(r*8.-uT*1.55)-.5)*16.)*uWarp;c+=mix(uA,uC,r)*tunnel*.62;float flare=exp(-length(uv-uP*.12)*9.)*(.012+.032*uAudio);c+=uC*flare;float vign=smoothstep(.9,.18,r);c*=mix(.72,1.,vign);o=vec4(c,1.);}`);
    this.pointP=program(gl,`#version 300 es\nprecision highp float;layout(location=0)in vec3 aP;layout(location=1)in float aS;uniform mat4 uVP;uniform float uT,uAudio;out float s;void main(){vec3 p=aP;float q=sin(uT*.2+aS*31.)*.7;p.xz*=1.+q*.004;p.y+=sin(uT*.5+aS*18.)*(.08+uAudio*.26);vec4 z=uVP*vec4(p,1);gl_Position=z;gl_PointSize=(1.0+aS*2.4+uAudio*1.8)*(180./max(1.,z.w));s=aS;}`,`#version 300 es\nprecision highp float;in float s;uniform vec3 uA,uB;out vec4 o;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;float a=(1.-d*2.)*(.2+s*.55);o=vec4(mix(uA,uB,s),a);}`);
    const fsQuad=`#version 300 es\nout vec2 v;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);v=p;gl_Position=vec4(p*2.-1.,0,1);}`;
    this.brightP=program(gl,fsQuad,`#version 300 es\nprecision highp float;in vec2 v;uniform sampler2D uTex;uniform float uThreshold;out vec4 o;void main(){vec3 c=texture(uTex,v).rgb;float l=max(c.r,max(c.g,c.b));o=vec4(c*smoothstep(uThreshold,uThreshold+.35,l),1);}`);
    this.blurP=program(gl,fsQuad,`#version 300 es\nprecision highp float;in vec2 v;uniform sampler2D uTex;uniform vec2 uDir;out vec4 o;void main(){vec3 c=texture(uTex,v).rgb*.227027;c+=texture(uTex,v+uDir*1.384615).rgb*.316216;c+=texture(uTex,v-uDir*1.384615).rgb*.316216;c+=texture(uTex,v+uDir*3.230769).rgb*.070270;c+=texture(uTex,v-uDir*3.230769).rgb*.070270;o=vec4(c,1);}`);
    this.compP=program(gl,fsQuad,`#version 300 es\nprecision highp float;in vec2 v;uniform sampler2D uScene,uBloom;uniform float uExposure,uBloomAmt,uT,uWarp;out vec4 o;float h(vec2 p){return fract(sin(dot(p,vec2(41.13,289.7)))*43758.5453);}void main(){vec2 uv=v;float ca=.0022*uWarp;float r=texture(uScene,uv+vec2(ca,0)).r,g=texture(uScene,uv).g,b=texture(uScene,uv-vec2(ca,0)).b;vec3 c=vec3(r,g,b)+texture(uBloom,uv).rgb*uBloomAmt;c=vec3(1.)-exp(-c*uExposure);float vig=smoothstep(.92,.18,length(uv-.5));c*=mix(.74,1.,vig);c+=(h(uv*vec2(1700.,900.)+uT)-.5)*.018;o=vec4(c,1);}`);
  }
  setupGeometry(){this.geo={cube:this.upload(cube()),sphere:this.upload(sphere()),torus:this.upload(torus()),cylinder:this.upload(cylinder()),octa:this.upload(octa())};this.lineId=0;const count=7000,pos=new Float32Array(count*3),seed=new Float32Array(count);for(let i=0;i<count;i++){const r=35+Math.random()*185,a=Math.random()*TAU,y=(Math.random()-.5)*120;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=y;pos[i*3+2]=Math.sin(a)*r;seed[i]=Math.random()}const gl=this.gl;this.pVAO=gl.createVertexArray();gl.bindVertexArray(this.pVAO);let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,pos,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,seed,gl.STATIC_DRAW);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,1,gl.FLOAT,false,0,0);gl.bindVertexArray(null);this.pCount=count;}
  upload(g){const gl=this.gl,vao=gl.createVertexArray();gl.bindVertexArray(vao);let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(g.p),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(g.n),gl.STATIC_DRAW);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,0,0);let count=g.p.length/3,indexed=false;if(g.i){b=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,b);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(g.i),gl.STATIC_DRAW);count=g.i.length;indexed=true}gl.bindVertexArray(null);return {vao,count,indexed,line:g.line};}
  addLine(points){const id='line'+(++this.lineId);this.geo[id]=this.upload(line(points));return id;}
  setupTargets(){const gl=this.gl;this.sceneF=gl.createFramebuffer();this.sceneT=gl.createTexture();this.depth=gl.createRenderbuffer();this.bloomF=[gl.createFramebuffer(),gl.createFramebuffer()];this.bloomT=[gl.createTexture(),gl.createTexture()];}
  allocTargets(){const gl=this.gl,w=this.canvas.width,h=this.canvas.height;gl.bindTexture(gl.TEXTURE_2D,this.sceneT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.bindRenderbuffer(gl.RENDERBUFFER,this.depth);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,w,h);gl.bindFramebuffer(gl.FRAMEBUFFER,this.sceneF);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,this.sceneT,0);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,this.depth);const bw=Math.max(2,Math.floor(w/2)),bh=Math.max(2,Math.floor(h/2));this.bw=bw;this.bh=bh;for(let i=0;i<2;i++){gl.bindTexture(gl.TEXTURE_2D,this.bloomT[i]);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,bw,bh,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.bindFramebuffer(gl.FRAMEBUFFER,this.bloomF[i]);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,this.bloomT[i],0)}gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
  obj(route,geo,opt={}){const o={geo,pos:opt.pos||[0,0,0],rot:opt.rot||[0,0,0],scale:opt.scale||[1,1,1],color:hex(opt.color||'#ffffff'),accent:hex(opt.accent||opt.color||'#ffffff'),e:opt.e??.5,a:opt.a??1,add:!!opt.add,spin:opt.spin||[0,0,0],float:opt.float||0,fs:opt.fs||1,phase:opt.phase??Math.random()*TAU,routeTo:opt.routeTo||null,radius:opt.radius||1.4,orbit:opt.orbit||null,ufo:opt.ufo||null,beamPulse:!!opt.beamPulse,mapRoute:opt.mapRoute||null,mapLink:opt.mapLink||null,searchIndex:opt.searchIndex??-1,explode:opt.explode!==false,baseScale:[...(opt.scale||[1,1,1])]};this.scenes[route].push(o);if(o.routeTo)this.interactives.push(o);return o;}
  ring(route,pos,radius,color,opt={}){return this.obj(route,'torus',{pos,scale:[radius,radius,radius],rot:opt.rot||[0,0,0],spin:opt.spin||[0,.08,0],color,accent:opt.accent||color,e:opt.e??1.2,a:opt.a??.45,add:true,float:opt.float||0,mapRoute:opt.mapRoute||null,searchIndex:opt.searchIndex??-1,explode:opt.explode});}
  buildScenes(){this.scenes={home:[],projects:[],cyber:[],about:[],contact:[],map:[],search:[]};projects.forEach(p=>this.scenes['project/'+p.slug]=[]);this.buildHome();this.buildProjects();projects.forEach(p=>this.buildProject(p));this.buildCyber();this.buildAbout();this.buildContact();this.buildMap();this.buildSearch();Object.keys(this.scenes).forEach((r,i)=>this.buildUFOFleet(r,i));}
  buildUFOFleet(route,seed=0){const p=this.presets[route]||this.presets.home;const c1=p.colors[0],c2=p.colors[2];const count=route==='map'?6:route==='search'?4:3;for(let i=0;i<count;i++)this.addUFO(route,{radius:17+i*4.6+(seed%3)*1.3,height:5+(i%3)*3.2,phase:i*2.07+seed*.77,speed:(i%2?-.018:.015)*(1+i*.12),wobble:.7+i*.12,color:i%2?c1:c2,accent:i%2?c2:c1,size:.72+i*.11});}
  addUFO(route,u){const shared={radius:u.radius,height:u.height,phase:u.phase,speed:u.speed,wobble:u.wobble};this.obj(route,'sphere',{pos:[0,0,0],scale:[1.55*u.size,.28*u.size,1.55*u.size],color:'#101316',accent:u.color,e:.72,a:.72,ufo:shared,explode:false});this.obj(route,'sphere',{pos:[0,.36*u.size,0],scale:[.72*u.size,.38*u.size,.72*u.size],color:u.accent,accent:'#ffffff',e:1.25,a:.48,add:true,ufo:shared,explode:false});this.obj(route,'torus',{pos:[0,.03*u.size,0],scale:[1.42*u.size,1.42*u.size,1.42*u.size],rot:[Math.PI/2,0,0],spin:[0,.45,0],color:u.color,accent:u.accent,e:1.65,a:.58,add:true,ufo:shared,explode:false});this.obj(route,'cylinder',{pos:[0,-1.25*u.size,0],scale:[.36*u.size,1.45*u.size,.36*u.size],color:u.color,accent:u.accent,e:1.05,a:.14,add:true,ufo:shared,beamPulse:true,explode:false});}
  buildHome(){const r='home';this.obj(r,'sphere',{scale:[2.8,2.8,2.8],color:'#24111c',accent:'#ff744f',e:1.45,a:.76,add:true,float:.15});for(let i=0;i<9;i++){this.ring(r,[0,0,0],4.7+i*.58,i%2?'#fff0ad':'#8159ff',{rot:[i*.31,i*.17,i*.26],spin:[.025+i*.006,.05*(i%2?1:-1),.018],a:.32+(i<3?.12:0),t:.028});}for(let i=0;i<24;i++){const a=i/24*TAU,rr=8.3+(i%4)*.75;this.obj(r,i%3===0?'octa':'cube',{pos:[Math.cos(a)*rr,Math.sin(a*2.5)*2.4,Math.sin(a)*rr],scale:[.15+.08*(i%3),.15+.08*(i%3),.7+(i%5)*.2],rot:[a*.3,a,.2],spin:[.08,.13,.04],color:i%4===0?'#ff744f':'#f8eed1',accent:'#8159ff',e:.75,a:.72,float:.2,fs:.7+i*.01});}const ribbon=[];for(let i=0;i<320;i++){const u=i/319*TAU*3,radius=6.2+Math.sin(u*2.7)*1.15;ribbon.push([Math.cos(u)*radius,Math.sin(u*1.55)*2.2,Math.sin(u)*radius])}this.obj(r,this.addLine(ribbon),{color:'#fff0ad',accent:'#fff0ad',e:1.6,a:.72,add:true,spin:[0,.03,0]});}
  buildProjects(){const r='projects',path=[];projects.forEach((p,i)=>{const a=i/projects.length*TAU-.6,rad=7.2,y=(i-(projects.length-1)/2)*3.7,x=Math.cos(a)*rad,z=Math.sin(a)*rad;path.push([x,y,z]);this.obj(r,'cube',{pos:[x,y,z],scale:[2.25,3.25,.38],rot:[0,-a+.25,.03*i],color:p.accent,accent:'#ffffff',e:.92,a:.86,float:.16,routeTo:'project/'+p.slug,radius:2.6});this.ring(r,[x,y,z],3.15,p.accent,{rot:[Math.PI/2,0,0],spin:[0,.22+i*.04,0],a:.42,t:.025});for(let q=0;q<7;q++){const aa=q/7*TAU;this.obj(r,'sphere',{pos:[x+Math.cos(aa)*3.6,y+Math.sin(aa)*2.0,z+Math.sin(aa)*.6],scale:[.09,.09,.09],color:'#fff4cb',accent:p.accent,e:1.8,a:.78,add:true,float:.15})}});this.obj(r,this.addLine(path),{color:'#ffffff',accent:'#ffffff',e:1.2,a:.22,add:true});for(let i=0;i<64;i++){const a=i/64*TAU*3;this.obj(r,'sphere',{pos:[Math.cos(a)*5.1,(i-32)*.26,Math.sin(a)*5.1],scale:[.055,.055,.055],color:i%2?'#19e6ff':'#ff2ea6',accent:'#fff',e:1.6,a:.55,add:true,float:.08});}}
  buildProject(p){const r='project/'+p.slug;if(p.realm==='ruvigil')return this.buildRuVigil(r,p);if(p.realm==='phantom')return this.buildPhantom(r,p);if(p.realm==='elif')return this.buildElif(r,p);this.obj(r,'octa',{scale:[3,3,3],color:p.accent,accent:'#fff',e:1.1,a:.72,add:true});for(let i=0;i<10;i++)this.ring(r,[0,0,0],4.2+i*.5,i%2?p.accent:'#fff',{rot:[i*.22,i*.17,i*.29],spin:[.03,.05,.02],a:.3});}
  buildRuVigil(r,p){for(let i=0;i<5;i++){const a=i/5*TAU,x=Math.cos(a)*6.7,z=Math.sin(a)*6.7;this.obj(r,'cylinder',{pos:[x,0,z],scale:[.45,3.4,.45],color:'#d7eff1',accent:p.accent,e:.42,a:.78});this.obj(r,'octa',{pos:[x,3.8,z],scale:[.62,.62,.62],color:'#ffca64',accent:p.accent,e:1.55,a:.92,add:true,float:.14,fs:1.2+i*.05});for(let k=0;k<4;k++)this.ring(r,[x,1.5-k*.72,z],1.0+k*.27,p.accent,{rot:[Math.PI/2,0,0],spin:[0,.18+k*.05,0],a:.32,t:.022});}for(let k=0;k<9;k++)this.ring(r,[0,0,0],2+k*1.05,k%2?p.accent:'#ffca64',{rot:[Math.PI/2,0,0],spin:[0,.035+k*.01,0],a:.16+(k<3?.12:0),t:.022});this.obj(r,'sphere',{pos:[0,3.2,0],scale:[.58,.58,.58],color:'#ffca64',accent:p.accent,e:1.5,a:.68,add:true});this.obj(r,'cylinder',{pos:[0,.9,0],scale:[.7,1.6,.7],color:'#113137',accent:p.accent,e:.82,a:.42,add:true,float:.04});for(let i=0;i<16;i++){const a=i/16*TAU;this.obj(r,'sphere',{pos:[Math.cos(a)*9,Math.sin(a*3)*1.8,Math.sin(a)*9],scale:[.08,.08,.08],color:p.accent,accent:'#fff',e:1.8,a:.65,add:true,float:.2,fs:1+i*.02});}}
  buildPhantom(r,p){for(let i=0;i<180;i++){const th=Math.random()*TAU,ph=Math.acos(2*Math.random()-1),rad=4.2*(.85+Math.random()*.22);let x=Math.sin(ph)*Math.cos(th)*rad,y=Math.cos(ph)*rad*1.18,z=Math.sin(ph)*Math.sin(th)*rad*.68;if(y>.2&&z>2.2&&Math.abs(x)<1)z+=.35;this.obj(r,'sphere',{pos:[x,y,z],scale:[.045,.045,.045],color:i%5===0?'#8dffd9':p.accent,accent:'#fff',e:1.5,a:.78,add:true,float:.05,fs:.8+Math.random()*.5,explode:false});}for(let i=0;i<5;i++){const a=i/5*TAU;this.obj(r,'octa',{pos:[Math.cos(a)*7,Math.sin(i)*1.5,Math.sin(a)*7],scale:[.5,.5,.5],color:i%2?'#8dffd9':p.accent,accent:'#fff',e:1.7,a:.86,add:true,spin:[.5,.8,.3],float:.16});this.ring(r,[Math.cos(a)*7,Math.sin(i)*1.5,Math.sin(a)*7],1.1,i%2?'#8dffd9':p.accent,{rot:[Math.PI/2,0,0],spin:[0,.35,0],a:.32,t:.02});}for(let i=0;i<7;i++)this.ring(r,[0,0,0],5+i*.55,i%2?p.accent:'#8dffd9',{rot:[i*.41,i*.21,i*.29],spin:[.025,.045,.018],a:.13,t:.018});}
  buildElif(r,p){this.obj(r,'cylinder',{scale:[3.1,2.4,3.1],color:'#11180c',accent:p.accent,e:.75,a:.92,spin:[0,.08,0]});this.obj(r,'sphere',{scale:[1.35,1.35,1.35],color:'#2d100c',accent:'#ff5038',e:1.45,a:.78,add:true,float:.06});for(let i=0;i<10;i++)this.ring(r,[0,0,0],3.8+i*.48,i%2?p.accent:'#ff5038',{rot:[i*.19,Math.PI/2*(i%2),i*.12],spin:[.025,.05*(i%2?1:-1),.02],a:.38,t:.025});for(let i=0;i<28;i++){const a=i/28*TAU,rad=8+(i%4)*.55;this.obj(r,'cube',{pos:[Math.cos(a)*rad,Math.sin(a*4)*1.4,Math.sin(a)*rad],scale:[.22,.22,1.0+(i%5)*.25],rot:[a*.2,a,.4],spin:[.08,.12,.03],color:i%3===0?'#ff5038':p.accent,accent:'#eef9ce',e:.75,a:.64,float:.13});}}
  buildCyber(){const r='cyber';for(let i=0;i<44;i++){const x=(i%8-3.5)*2.1,y=(Math.floor(i/8)-2.5)*1.9,z=((i*7)%7-3)*1.2;this.obj(r,i%5===0?'octa':'cube',{pos:[x,y,z],scale:[.35+((i*3)%4)*.16,.35,.35+((i*5)%4)*.16],rot:[i*.19,i*.39,i*.13],spin:[.12,.18,.07],color:i%4===0?'#ff5a1f':'#26231a',accent:'#faff00',e:.72,a:.84,float:.18,fs:1.15});}for(let i=0;i<8;i++)this.ring(r,[0,0,0],3+i*.95,i%2?'#faff00':'#ff5a1f',{rot:[i*.35,i*.27,i*.18],spin:[.04,.1*(i%2?1:-1),.03],a:.38,t:.025});const pts=[];for(let i=0;i<120;i++)pts.push([(i%12-6)*1.3,(Math.floor(i/12)-5)*1.1,Math.sin(i*.73)*2.1]);this.obj(r,this.addLine(pts),{color:'#faff00',accent:'#faff00',e:1.8,a:.16,add:true});}
  buildAbout(){const r='about';this.obj(r,'sphere',{scale:[2.1,2.1,2.1],color:'#3a2312',accent:'#fff4bd',e:1.25,a:.66,add:true,float:.08,explode:false});for(let h=0;h<3;h++){const helix=[];for(let i=0;i<90;i++){const a=i/89*TAU*2.4+h*2.1,rad=3.4+h*.52;helix.push([Math.cos(a)*rad,(i/89-.5)*9,Math.sin(a)*rad])}this.obj(r,this.addLine(helix),{color:h===0?'#ffd87a':h===1?'#7d52ff':'#26e6b4',accent:'#fff',e:1.25,a:.28,add:true,spin:[0,.028*(h%2?1:-1),0]});}skills.slice(0,12).forEach((sk,i)=>{const a=i/12*TAU,rad=5.2+(i%4)*1.25,y=Math.sin(a*2.3)*2.0;const col=i%3===0?'#ffd87a':i%3===1?'#7d52ff':'#26e6b4';this.ring(r,[0,0,0],rad,col,{rot:[Math.PI/2+i*.06,0,i*.09],spin:[0,.015*(i%2?1:-1),0],a:.085,t:.018,explode:false});this.obj(r,i%3===0?'octa':i%3===1?'sphere':'cube',{pos:[Math.cos(a)*rad,y,Math.sin(a)*rad],scale:[.28+.08*(i%3),.28+.08*(i%3),.28+.08*(i%3)],color:col,accent:'#fff4bd',e:1.25,a:.84,orbit:{radius:rad,speed:.035+i*.004,phase:a,y:y},explode:false});});for(let i=0;i<14;i++){const a=i/14*TAU,rr=10.5+(i%3)*.8;this.obj(r,'cube',{pos:[Math.cos(a)*rr,Math.sin(a*2.2)*2.4,Math.sin(a)*rr],scale:[.10,.10,.8+(i%4)*.2],rot:[a*.3,a,.2],spin:[.035,.06,.018],color:'#fff4bd',accent:'#7d52ff',e:.58,a:.38,float:.12});}}
  buildContact(){const r='contact';this.obj(r,'octa',{scale:[2.8,4.6,2.8],color:'#eafff6',accent:'#88ffd5',e:1.05,a:.52,add:true,spin:[.035,.11,.025],float:.08});for(let i=0;i<8;i++){const a=i/8*TAU;this.obj(r,'cylinder',{pos:[Math.cos(a)*6.7,0,Math.sin(a)*6.7],scale:[.18,3.9,.18],rot:[0,0,(i-3.5)*.045],color:i%3===0?'#ff9b78':i%3===1?'#88ffd5':'#6755ff',accent:'#fff',e:1.25,a:.52,add:true});this.ring(r,[Math.cos(a)*6.7,0,Math.sin(a)*6.7],1.1,i%2?'#88ffd5':'#ff9b78',{rot:[Math.PI/2,0,0],spin:[0,.28,0],a:.32,t:.022});}for(let i=0;i<6;i++)this.ring(r,[0,0,0],4+i*.9,i%2?'#88ffd5':'#6755ff',{rot:[i*.26,i*.34,i*.17],spin:[.025,.065,.02],a:.28,t:.022});}
  buildMap(){const r='map';this.mapAnchors=[];const nodes=[['home',0,3,0,'#fff0ad'],['projects',0,-1,0,'#ff2ea6'],['cyber',-9,-5,-3,'#faff00'],['about',0,-7,4,'#26e6b4'],['contact',9,-5,-3,'#88ffd5']];projects.forEach((p,i)=>{const a=(i/(Math.max(1,projects.length)))*TAU-.4;nodes.push(['project/'+p.slug,Math.cos(a)*9,8+Math.sin(a*1.7)*2,Math.sin(a)*6,p.accent])});nodes.forEach((n,i)=>{const o=this.obj(r,i<5?'sphere':'octa',{pos:[n[1],n[2],n[3]],scale:[i<5?.72:.62,i<5?.72:.62,i<5?.72:.62],color:n[4],accent:'#fff',e:1.7,a:.9,add:true,float:.2,routeTo:n[0],radius:2.2,mapRoute:n[0],explode:false});this.mapAnchors.push({route:n[0],obj:o});this.ring(r,[n[1],n[2],n[3]],i<5?1.65:1.35,n[4],{rot:[Math.PI/2+i*.08,0,i*.06],spin:[0,.15+i*.012,0],a:.36,t:.025,mapRoute:n[0],explode:false});this.ring(r,[n[1],n[2],n[3]],i<5?2.15:1.8,'#ffffff',{rot:[i*.11,Math.PI/2,i*.07],spin:[.04,.06,0],a:.10,t:.018,mapRoute:n[0],explode:false});});const byRoute=Object.fromEntries(nodes.map(n=>[n[0],[n[1],n[2],n[3]]]));const edges=[['home','projects'],['projects','cyber'],['projects','about'],['projects','contact'],...projects.map(p=>['projects','project/'+p.slug]),...projects.map((p,i)=>['project/'+p.slug,projects[(i+1)%projects.length]?'project/'+projects[(i+1)%projects.length].slug:'projects'])];edges.forEach((e,i)=>{const a=byRoute[e[0]],b=byRoute[e[1]];if(!a||!b)return;const mid=[(a[0]+b[0])/2+Math.sin(i)*1.7,(a[1]+b[1])/2+2.2,(a[2]+b[2])/2+Math.cos(i)*2.4];this.obj(r,this.addLine([a,mid,b]),{color:i%3===0?'#6ce8ff':i%3===1?'#ff5d98':'#fff0ae',accent:'#fff',e:1.45,a:.26,add:true,mapLink:e,explode:false});});for(let q=0;q<5;q++)this.ring(r,[0,0,0],5.5+q*2.2,q%2?'#6ce8ff':'#ff5d98',{rot:[Math.PI/2+q*.17,q*.08,q*.13],spin:[.01,.018*(q%2?1:-1),.008],a:.07,t:.014,explode:false});for(let i=0;i<28;i++){const a=i/28*TAU,rad=14+(i%4)*.9;this.obj(r,'cube',{pos:[Math.cos(a)*rad,Math.sin(a*3)*3.5,Math.sin(a)*rad],scale:[.07,.07,.55+(i%4)*.15],rot:[a*.3,a,.2],spin:[.035,.055,.018],color:'#fff',accent:'#6ce8ff',e:.55,a:.24,float:.12,explode:false});}}
  buildSearch(){const r='search';this.searchNodes=[];for(let i=0;i<44;i++){const a=i/44*TAU,rad=8+(i%5)*1.1;this.obj(r,i%6===0?'octa':'cube',{pos:[Math.cos(a)*rad,Math.sin(a*3.2)*3.2,Math.sin(a)*rad],scale:[.08,.08,.55+(i%4)*.18],rot:[a,a*.3,.1],spin:[.055,.09,.025],color:i%2?'#ffffff':'#ff5d98',accent:'#6ce8ff',e:.62,a:.20,float:.18,explode:false});}const positions=[[-5.4,1.6,0],[0,0,-1.2],[5.4,1.6,0]];for(let i=0;i<3;i++){const o=this.obj(r,'octa',{pos:positions[i],scale:[.78,.78,.78],color:i===0?'#ff5d98':'#6ce8ff',accent:'#fff',e:1.9,a:.88,add:true,float:.18,routeTo:null,radius:2.3,searchIndex:i,explode:false});this.searchNodes.push(o);this.ring(r,positions[i],1.45,i===0?'#ff5d98':'#6ce8ff',{rot:[Math.PI/2,0,0],spin:[0,.17+i*.03,0],a:.34,t:.022,searchIndex:i,explode:false});this.ring(r,positions[i],2.1,'#ffffff',{rot:[i*.17,Math.PI/2,i*.11],spin:[.05,.04,0],a:.09,t:.018,searchIndex:i,explode:false});}for(let k=0;k<4;k++)this.ring(r,[0,0,0],5.8+k*1.45,k%2?'#ff5d98':'#6ce8ff',{rot:[Math.PI/2+k*.18,k*.11,k*.08],spin:[.015,.03*(k%2?1:-1),.01],a:.10,t:.018,explode:false});}
  setSearchResults(results){this.searchNodes.forEach((o,i)=>{const hit=results?.[i];o.routeTo=hit?.route||null;o.a=hit?.96:.08;o.e=hit?2.0:.2;const v=hit?.score||0,oScale=hit?.82+Math.min(.28,v*.018):.26;o.baseScale=[oScale,oScale,oScale];o.scale=[...o.baseScale];o.color=hit?hex(i===0?'#ff5d98':i===1?'#6ce8ff':'#fff0ae'):hex('#302d36');});}
  setSearchFocus(i=0){this.searchFocus=i;}
  setMapFocus(route=null){this.mapFocus=route;}
  setRoute(route,instant=false){if(!this.scenes[route])route='home';if(route===this.route&&!instant)return;this.prevRoute=instant?null:this.route;this.route=route;this.transition=instant?1:0;this.transitionStart=performance.now();this.paletteFrom={a:[...this.palette.a],b:[...this.palette.b],c:[...this.palette.c]};const p=this.presets[route]||this.presets.home;this.paletteTo={a:hex(p.colors[0]),b:hex(p.colors[1]),c:hex(p.colors[2])};this.yaw=0;this.pitch=0;this.zoom=1;}
  setAudioLevel(v){this.audio=clamp(v||0,0,1);}
  toggleExplode(){this.exploded=!this.exploded;this.explodeTarget=this.exploded?1:0;return this.exploded;}
  reset(){this.yaw=this.pitch=0;this.zoom=1;}
  search(query){const q=(query||'').trim().toLowerCase();const pool=[{label:'Origin',route:'home',type:'Realm',keywords:'home origin build break evolve robotics ai security'},{label:'Project Archive',route:'projects',type:'Realm',keywords:'projects archive work portfolio'},{label:'Breach / Cybersecurity',route:'cyber',type:'Realm',keywords:'ctf cybersecurity reverse engineering pwn forensics'},{label:'About / Orbit',route:'about',type:'Realm',keywords:'about skills profile identity robotics artificial intelligence'},{label:'Contact / Uplink',route:'contact',type:'Realm',keywords:'contact github linkedin ctftime social'}].concat(projects.map(p=>({label:p.name,route:'project/'+p.slug,type:'Project',keywords:(p.name+' '+p.tagline+' '+p.stack.join(' ')).toLowerCase()})));if(!q)return pool.slice(0,5);const tokens=q.split(/\s+/).filter(Boolean);const score=x=>tokens.reduce((n,t)=>{const hay=(x.label+' '+x.keywords).toLowerCase();if(x.label.toLowerCase().startsWith(t))n+=8;else if(x.label.toLowerCase().includes(t))n+=5;if(hay.includes(t))n+=3;return n;},0);return pool.map(x=>({...x,score:score(x)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,5);}
  projectWorld(p){const q=projectPoint(this.vp,p);return {x:(q[0]*.5+.5)*innerWidth,y:(1-(q[1]*.5+.5))*innerHeight,z:q[2],visible:q[3]>0&&q[2]<1.2};}
  getMapAnchors(){if(this.route!=='map')return[];return this.mapAnchors.map(x=>({route:x.route,pos:this.projectWorld(x.obj._renderPos||x.obj.pos)}));}
  resize(){const dpr=Math.max(.72,Math.min(devicePixelRatio||1,this.dprCap)*this.qualityScale);this.canvas.width=Math.max(2,Math.floor(innerWidth*dpr));this.canvas.height=Math.max(2,Math.floor(innerHeight*dpr));this.canvas.style.width=innerWidth+'px';this.canvas.style.height=innerHeight+'px';this.allocTargets();}
  bind(){addEventListener('resize',()=>this.resize());addEventListener('pointermove',e=>{this.pointer=[e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2];if(this.drag){const dx=e.clientX-this.dragStart[0],dy=e.clientY-this.dragStart[1];if(Math.abs(dx)+Math.abs(dy)>4)this.dragMoved=true;this.yaw=this.dragYaw-dx*.0042;this.pitch=clamp(this.dragPitch-dy*.0032,-.55,.55)}});addEventListener('pointerdown',e=>{if(e.button||e.target.closest('button,a,input,.overlay,.lens,.topbar,.phase-dial'))return;this.drag=true;this.dragMoved=false;this.dragStart=[e.clientX,e.clientY];this.dragYaw=this.yaw;this.dragPitch=this.pitch});addEventListener('pointerup',()=>{if(this.drag&&!this.dragMoved&&this.hover?.routeTo&&this.onNavigate)this.onNavigate(this.hover.routeTo);this.drag=false});addEventListener('wheel',e=>{if(e.target.closest('.lens,.overlay'))return;this.zoom=clamp(this.zoom+Math.sign(e.deltaY)*.07,.7,1.42)},{passive:true});}
  renderObj(o,alpha,t,index){const gl=this.gl,g=this.geo[o.geo];if(!g)return;let p=[...o.pos],rot=[o.rot[0]+o.spin[0]*t,o.rot[1]+o.spin[1]*t,o.rot[2]+o.spin[2]*t],scale=[...o.baseScale];if(o.float)p[1]+=Math.sin(t*o.fs+o.phase)*o.float;if(o.orbit){const a=t*(o.orbit.speed||.15)+(o.orbit.phase||o.phase);p=[Math.cos(a)*o.orbit.radius,(o.orbit.y||0)+Math.sin(a*1.7)*.5,Math.sin(a)*o.orbit.radius]}if(o.ufo){const a=t*o.ufo.speed+o.ufo.phase;p=[Math.cos(a)*o.ufo.radius+o.pos[0],o.ufo.height+Math.sin(a*1.9)*o.ufo.wobble+o.pos[1],Math.sin(a)*o.ufo.radius+o.pos[2]];rot[1]+=-a+Math.PI/2;if(o.beamPulse){const q=.35+.65*(.5+.5*Math.sin(t*1.8+o.ufo.phase));scale[1]*=q;scale[0]*=.78+.22*q;scale[2]*=.78+.22*q;}}if(this.explodeAmount>.002&&o.explode){const d=norm([p[0]||Math.sin(index*1.7),p[1]||Math.cos(index*.9),p[2]||Math.sin(index*.7+.3)]),amp=(5.5+(index%7)*.55)*this.explodeAmount;p=[p[0]+d[0]*amp,p[1]+d[1]*amp,p[2]+d[2]*amp];rot[0]+=d[2]*this.explodeAmount*.7;rot[2]+=d[0]*this.explodeAmount*.7;}if(this.mapFocus&&o.mapLink)alpha*=o.mapLink.includes(this.mapFocus)?1.35:.10;if(o.mapRoute&&this.mapFocus){const focused=o.mapRoute===this.mapFocus;scale=scale.map(v=>v*(focused?1.45:.82));alpha*=focused?1:.30;}if(o.searchIndex>=0){const focused=o.searchIndex===this.searchFocus;scale=scale.map(v=>v*(focused?1.22:.88));alpha*=focused?1:.58;}o._renderPos=p;const M=trs(p,rot,scale);gl.useProgram(this.meshP);gl.uniformMatrix4fv(this.U(this.meshP,'uM'),false,M);gl.uniformMatrix4fv(this.U(this.meshP,'uVP'),false,this.vp);gl.uniform3fv(this.U(this.meshP,'uC'),o.color);gl.uniform3fv(this.U(this.meshP,'uA'),o.accent);gl.uniform1f(this.U(this.meshP,'uE'),o.e*(1+this.audio*.22));gl.uniform1f(this.U(this.meshP,'uAlpha'),o.a*alpha);gl.uniform1f(this.U(this.meshP,'uT'),t);gl.uniform1f(this.U(this.meshP,'uAudio'),this.audio);gl.bindVertexArray(g.vao);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,o.add?gl.ONE:gl.ONE_MINUS_SRC_ALPHA);if(g.line)gl.drawArrays(gl.LINE_STRIP,0,g.count);else if(g.indexed)gl.drawElements(gl.TRIANGLES,g.count,gl.UNSIGNED_SHORT,0);else gl.drawArrays(gl.TRIANGLES,0,g.count);}
  renderRoute(route,alpha,t){if(!route||alpha<=.001)return;(this.scenes[route]||[]).forEach((o,i)=>this.renderObj(o,alpha,t,i));}
  drawBackground(t,warp){const gl=this.gl;gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.useProgram(this.bgP);gl.uniform1f(this.U(this.bgP,'uT'),t);gl.uniform1f(this.U(this.bgP,'uWarp'),warp);gl.uniform1f(this.U(this.bgP,'uAudio'),this.audio);gl.uniform3fv(this.U(this.bgP,'uA'),this.palette.a);gl.uniform3fv(this.U(this.bgP,'uB'),this.palette.b);gl.uniform3fv(this.U(this.bgP,'uC'),this.palette.c);gl.uniform2fv(this.U(this.bgP,'uP'),this.pointerSmooth);const mode={home:0,projects:1,'project/ruvigil':2,'project/phantom':3,'project/elif-linux':4,cyber:5,about:6,contact:7,map:8,search:9}[this.route]??0;gl.uniform1f(this.U(this.bgP,'uMode'),mode);gl.drawArrays(gl.TRIANGLES,0,3);}
  drawParticles(t){const gl=this.gl;gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.enable(gl.DEPTH_TEST);gl.depthMask(false);gl.useProgram(this.pointP);gl.uniformMatrix4fv(this.U(this.pointP,'uVP'),false,this.vp);gl.uniform1f(this.U(this.pointP,'uT'),t);gl.uniform1f(this.U(this.pointP,'uAudio'),this.audio);gl.uniform3fv(this.U(this.pointP,'uA'),this.palette.a);gl.uniform3fv(this.U(this.pointP,'uB'),this.palette.b);gl.bindVertexArray(this.pVAO);gl.drawArrays(gl.POINTS,0,Math.floor(this.pCount*this.particleRatio));gl.depthMask(true);}
  updateCamera(){const p=this.presets[this.route]||this.presets.home;let base=[...p.cam],target=[...p.target];if(this.transition<1&&this.prevRoute){const pp=this.presets[this.prevRoute]||this.presets.home,e=ease(this.transition);base=[lerp(pp.cam[0],p.cam[0],e)+Math.sin(e*Math.PI)*6,lerp(pp.cam[1],p.cam[1],e)+Math.sin(e*Math.PI)*7,lerp(pp.cam[2],p.cam[2],e)-Math.sin(e*Math.PI)*3];target=[lerp(pp.target[0],p.target[0],e),lerp(pp.target[1],p.target[1],e),lerp(pp.target[2],p.target[2],e)]}else{const c=Math.cos(this.yaw),s=Math.sin(this.yaw),x=base[0]*c+base[2]*s,z=-base[0]*s+base[2]*c;base=[x*this.zoom,base[1]*this.zoom+this.pitch*8,z*this.zoom]}base[0]+=this.pointerSmooth[0]*.55;base[1]+=this.pointerSmooth[1]*.28;this.view=look(base,target);this.proj=persp(47*Math.PI/180,this.canvas.width/this.canvas.height,.1,500);this.vp=mm(this.proj,this.view);}
  pick(){let best=null,bestD=1e9;const px=innerWidth*(this.pointer[0]*.5+.5),py=innerHeight*(1-(this.pointer[1]*.5+.5));(this.scenes[this.route]||[]).filter(o=>o.routeTo).forEach(o=>{const p=this.projectWorld(o._renderPos||o.pos);if(!p.visible)return;const d=Math.hypot(p.x-px,p.y-py);if(d<58*o.radius&&d<bestD){best=o;bestD=d}});if(best!==this.hover){this.hover=best;document.body.classList.toggle('cursor-hot',!!best);this.onHover?.(best?.routeTo||null);}}
  post(t,warp){const gl=this.gl;gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.viewport(0,0,this.bw,this.bh);gl.bindFramebuffer(gl.FRAMEBUFFER,this.bloomF[0]);gl.useProgram(this.brightP);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.sceneT);gl.uniform1i(this.U(this.brightP,'uTex'),0);gl.uniform1f(this.U(this.brightP,'uThreshold'),.62);gl.drawArrays(gl.TRIANGLES,0,3);for(let pass=0;pass<this.bloomPasses;pass++){const dst=(pass+1)%2,src=pass%2;gl.bindFramebuffer(gl.FRAMEBUFFER,this.bloomF[dst]);gl.useProgram(this.blurP);gl.bindTexture(gl.TEXTURE_2D,this.bloomT[src]);gl.uniform1i(this.U(this.blurP,'uTex'),0);gl.uniform2f(this.U(this.blurP,'uDir'),pass%2?0:1/this.bw,pass%2?1/this.bh:0);gl.drawArrays(gl.TRIANGLES,0,3)}gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.useProgram(this.compP);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.sceneT);gl.uniform1i(this.U(this.compP,'uScene'),0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,this.bloomT[this.bloomPasses%2]);gl.uniform1i(this.U(this.compP,'uBloom'),1);const p=this.presets[this.route]||this.presets.home;gl.uniform1f(this.U(this.compP,'uExposure'),p.exposure);gl.uniform1f(this.U(this.compP,'uBloomAmt'),p.bloom);gl.uniform1f(this.U(this.compP,'uT'),t);gl.uniform1f(this.U(this.compP,'uWarp'),warp);gl.drawArrays(gl.TRIANGLES,0,3);}
  adaptPerformance(dt,now){this.fpsAcc+=dt;this.fpsFrames++;if(this.fpsAcc<1.8)return;this.fps=this.fpsFrames/this.fpsAcc;this.fpsAcc=0;this.fpsFrames=0;if(now-this.lastQualityChange<3500)return;let changed=false;if(this.fps<43&&this.qualityScale>.68){this.qualityScale=Math.max(.68,this.qualityScale-.12);this.particleRatio=Math.max(.58,this.particleRatio-.14);this.bloomPasses=2;changed=true}else if(this.fps>57&&this.qualityScale<.99){this.qualityScale=Math.min(1,this.qualityScale+.08);this.particleRatio=Math.min(1,this.particleRatio+.1);this.bloomPasses=this.qualityScale>.86?4:2;changed=true}if(changed){this.lastQualityChange=now;this.resize();}}
  loop(now){const dt=Math.min(.05,(now-this.last)/1000);this.last=now;this.time+=dt;this.adaptPerformance(dt,now);this.explodeAmount=lerp(this.explodeAmount,this.explodeTarget,1-Math.pow(.001,dt));this.pointerSmooth[0]=lerp(this.pointerSmooth[0],this.pointer[0],.065);this.pointerSmooth[1]=lerp(this.pointerSmooth[1],this.pointer[1],.065);if(this.transition<1){this.transition=clamp((now-this.transitionStart)/this.transitionDuration,0,1);if(this.transition===1)this.prevRoute=null}const e=ease(this.transition);['a','b','c'].forEach(k=>{for(let i=0;i<3;i++)this.palette[k][i]=lerp(this.paletteFrom[k][i],this.paletteTo[k][i],e)});this.updateCamera();const warp=this.transition<1?Math.sin(this.transition*Math.PI):0;const gl=this.gl;gl.bindFramebuffer(gl.FRAMEBUFFER,this.sceneF);gl.viewport(0,0,this.canvas.width,this.canvas.height);this.drawBackground(this.time,warp);gl.enable(gl.DEPTH_TEST);gl.clear(gl.DEPTH_BUFFER_BIT);this.drawParticles(this.time);if(this.prevRoute)this.renderRoute(this.prevRoute,1-e,this.time);this.renderRoute(this.route,e,this.time);gl.bindFramebuffer(gl.FRAMEBUFFER,null);this.post(this.time,warp);this.pick();this.onFrame?.({time:this.time,route:this.route,transition:this.transition,map:this.getMapAnchors(),audio:this.audio,fps:this.fps,quality:this.qualityScale});requestAnimationFrame(this.loop);}
}
