(function(){
'use strict';
const D=window.AETER_DATA;
const TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
const hex=(h)=>{h=h.replace('#','');if(h.length===3)h=[...h].map(x=>x+x).join('');return [parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255];};
function v3(x=0,y=0,z=0){return [x,y,z]}
function sub(a,b){return [a[0]-b[0],a[1]-b[1],a[2]-b[2]]}
function cross(a,b){return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
function norm(a){const l=Math.hypot(a[0],a[1],a[2])||1;return [a[0]/l,a[1]/l,a[2]/l]}
function m4(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])}
function mm(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function persp(fov,aspect,n,f){const t=1/Math.tan(fov/2),o=new Float32Array(16);o[0]=t/aspect;o[5]=t;o[10]=(f+n)/(n-f);o[11]=-1;o[14]=2*f*n/(n-f);return o}
function look(eye,target,up=[0,1,0]){const z=norm(sub(eye,target)),x=norm(cross(up,z)),y=cross(z,x),o=m4();o[0]=x[0];o[1]=y[0];o[2]=z[0];o[4]=x[1];o[5]=y[1];o[6]=z[1];o[8]=x[2];o[9]=y[2];o[10]=z[2];o[12]=-(x[0]*eye[0]+x[1]*eye[1]+x[2]*eye[2]);o[13]=-(y[0]*eye[0]+y[1]*eye[1]+y[2]*eye[2]);o[14]=-(z[0]*eye[0]+z[1]*eye[1]+z[2]*eye[2]);return o}
function trs(p,r,s){let o=m4();const cx=Math.cos(r[0]),sx=Math.sin(r[0]),cy=Math.cos(r[1]),sy=Math.sin(r[1]),cz=Math.cos(r[2]),sz=Math.sin(r[2]);const rx=new Float32Array([1,0,0,0,0,cx,sx,0,0,-sx,cx,0,0,0,0,1]);const ry=new Float32Array([cy,0,-sy,0,0,1,0,0,sy,0,cy,0,0,0,0,1]);const rz=new Float32Array([cz,sz,0,0,-sz,cz,0,0,0,1,0,0,0,0,1]);const sc=new Float32Array([s[0],0,0,0,0,s[1],0,0,0,0,s[2],0,0,0,0,1]);o=mm(o,rx);o=mm(o,ry);o=mm(o,rz);o=mm(o,sc);o[12]=p[0];o[13]=p[1];o[14]=p[2];return o}
function projPoint(m,p){const x=p[0],y=p[1],z=p[2],w=m[3]*x+m[7]*y+m[11]*z+m[15];return [(m[0]*x+m[4]*y+m[8]*z+m[12])/w,(m[1]*x+m[5]*y+m[9]*z+m[13])/w,(m[2]*x+m[6]*y+m[10]*z+m[14])/w,w]}
function createShader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}
function program(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,createShader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,createShader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p}
function cube(){const p=[-1,-1,1,1,-1,1,1,1,1,-1,1,1,1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1,-1,1,1,1,1,1,1,1,-1,-1,1,-1,-1,-1,-1,-1,1,-1,1,1,1,-1,1,-1,1,-1,1,1,-1,1,1,-1,-1,-1,-1,1,-1,-1,1,-1,1,-1,1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1,1,1,-1];const n=[0,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,1,0,0,1,0,0,1,0,0,1,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0];const i=[];for(let f=0;f<6;f++){const a=f*4;i.push(a,a+1,a+2,a,a+2,a+3)}return {p,n,i}}
function sphere(lat=16,lon=24){const p=[],n=[],i=[];for(let y=0;y<=lat;y++){const v=y/lat,ph=v*Math.PI;for(let x=0;x<=lon;x++){const u=x/lon,th=u*TAU,s=Math.sin(ph);const px=Math.cos(th)*s,py=Math.cos(ph),pz=Math.sin(th)*s;p.push(px,py,pz);n.push(px,py,pz)}}for(let y=0;y<lat;y++)for(let x=0;x<lon;x++){const a=y*(lon+1)+x,b=a+lon+1;i.push(a,b,a+1,b,b+1,a+1)}return {p,n,i}}
function torus(R=1,r=.25,seg=48,tube=12){const p=[],n=[],i=[];for(let j=0;j<=tube;j++){const v=j/tube*TAU,cv=Math.cos(v),sv=Math.sin(v);for(let k=0;k<=seg;k++){const u=k/seg*TAU,cu=Math.cos(u),su=Math.sin(u);p.push((R+r*cv)*cu,r*sv,(R+r*cv)*su);n.push(cv*cu,sv,cv*su)}}for(let j=0;j<tube;j++)for(let k=0;k<seg;k++){const a=j*(seg+1)+k,b=a+seg+1;i.push(a,b,a+1,b,b+1,a+1)}return {p,n,i}}
function cylinder(seg=24){const p=[],n=[],i=[];for(let y=0;y<2;y++){const yy=y?1:-1;for(let k=0;k<=seg;k++){const a=k/seg*TAU,c=Math.cos(a),s=Math.sin(a);p.push(c,yy,s);n.push(c,0,s)}}for(let k=0;k<seg;k++){const a=k,b=k+seg+1;i.push(a,b,a+1,b,b+1,a+1)}return {p,n,i}}
function line(points){const p=[],n=[];points.forEach(q=>{p.push(...q);n.push(0,1,0)});return {p,n,i:null,line:true}}
class Engine{
 constructor(canvas){
  this.canvas=canvas;this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!this.gl)throw new Error('WebGL2 is unavailable in this browser.');const gl=this.gl;
  this.time=0;this.last=performance.now();this.route='home';this.prevRoute=null;this.transition=1;this.transitionStart=0;this.duration=1550;this.pointer=[0,0];this.pointerSmooth=[0,0];this.drag=false;this.dragMoved=false;this.yaw=0;this.pitch=0;this.zoom=1;this.audio=0;this.hover=null;this.interactives=[];this.searchHits=[];this.onNavigate=null;this.onHover=null;this.onFrame=null;
  this.palette={a:hex('#ff795c'),b:hex('#6d5cff'),c:hex('#ffe29a')};this.paletteFrom={...this.palette};this.paletteTo={...this.palette};
  this.presets={
   home:{cam:[14,6,25],target:[0,0,0],colors:['#ff795c','#6d5cff','#ffe29a'],exposure:.92,bloom:.8},
   projects:{cam:[12,5,27],target:[0,0,0],colors:['#ff2e93','#15d9ff','#fff2c6'],exposure:.88,bloom:.95},
   'project:ruvigil':{cam:[12,7,24],target:[0,1,0],colors:['#35f4ff','#ffb14a','#d7fff2'],exposure:.82,bloom:1.0},
   'project:phantom':{cam:[11,5,23],target:[0,0,0],colors:['#ff3db8','#816bff','#99ffd9'],exposure:.80,bloom:1.05},
   'project:elif-linux':{cam:[13,6,25],target:[0,0,0],colors:['#a9ff32','#ff5c45','#e9ffcc'],exposure:.78,bloom:.88},
   cyber:{cam:[15,7,27],target:[0,0,0],colors:['#f4ff38','#ff642f','#f4edda'],exposure:.76,bloom:.78},
   about:{cam:[12,7,27],target:[0,0,0],colors:['#ffc85b','#8b68ff','#5effb2'],exposure:.86,bloom:.82},
   contact:{cam:[10,6,24],target:[0,0,0],colors:['#7dffd6','#ff8b7c','#cfc2ff'],exposure:.86,bloom:.92},
   atlas:{cam:[0,3,32],target:[0,0,0],colors:['#66eaff','#ff5e9e','#fff0b0'],exposure:.82,bloom:.95},
   search:{cam:[0,1,29],target:[0,0,0],colors:['#ffffff','#ff5b8d','#77e8ff'],exposure:.82,bloom:.85}
  };
  this.setupPrograms();this.setupGeometry();this.setupTargets();this.buildScenes();this.resize();this.bind();this.setRoute('home',true);this.loop=this.loop.bind(this);requestAnimationFrame(this.loop);
 }
 setupPrograms(){const gl=this.gl;
  this.meshP=program(gl,`#version 300 es\nprecision highp float;layout(location=0)in vec3 aP;layout(location=1)in vec3 aN;uniform mat4 uM,uVP;out vec3 vN;out vec3 vW;void main(){vec4 w=uM*vec4(aP,1.);vW=w.xyz;vN=normalize(mat3(uM)*aN);gl_Position=uVP*w;}`,`#version 300 es\nprecision highp float;in vec3 vN;in vec3 vW;uniform vec3 uC,uA;uniform float uE,uAlpha,uT;out vec4 o;void main(){vec3 n=normalize(vN);vec3 l1=normalize(vec3(.35,.8,.55));vec3 l2=normalize(vec3(-.7,.2,-.5));float d=max(0.,dot(n,l1))*.72+max(0.,dot(n,l2))*.22;float rim=pow(1.-abs(dot(n,normalize(-vW))),2.4);float pulse=.5+.5*sin(uT*2.+vW.y*1.7+vW.x*.4);vec3 c=uC*(.16+d*.85)+uA*(rim*(.35+uE*.7))+uC*uE*(.14+.12*pulse);o=vec4(c,uAlpha);}`);
  this.bgP=program(gl,`#version 300 es\nout vec2 v;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);v=p;gl_Position=vec4(p*2.-1.,0,1);}`,`#version 300 es\nprecision highp float;in vec2 v;uniform float uT,uWarp;uniform vec3 uA,uB,uC;uniform vec2 uP;out vec4 o;float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+vec2(1,1)),f.x),f.y);}void main(){vec2 uv=v-.5;float r=length(uv);float a=atan(uv.y,uv.x);float f=n(v*4.+vec2(uT*.035,-uT*.02))+n(v*10.-uT*.015)*.35;vec3 c=mix(uB*.10,uA*.18+.02,f);c+=uC*(.03+pow(max(0.,sin(a*7.-uT*.25+f*4.)),14.)*.07)*(1.-smoothstep(.1,.78,r));float tunnel=exp(-abs(fract(r*7.-uT*1.8)-.5)*18.)*uWarp;c+=mix(uA,uC,r)*tunnel*.75;float grid=pow(max(0.,sin((v.x+f*.02)*120.)*sin((v.y-f*.02)*80.)),26.)*.025;c+=grid*uC;o=vec4(c,1);}`);
  this.pointP=program(gl,`#version 300 es\nprecision highp float;layout(location=0)in vec3 aP;layout(location=1)in float aS;uniform mat4 uVP;uniform float uT,uAudio;out float s;void main(){vec3 p=aP;float q=sin(uT*.2+aS*31.)*.7;p.xz*=1.+q*.004;p.y+=sin(uT*.5+aS*18.)*(.08+uAudio*.25);vec4 z=uVP*vec4(p,1);gl_Position=z;gl_PointSize=(1.2+aS*2.8+uAudio*2.)*(160./max(1.,z.w));s=aS;}`,`#version 300 es\nprecision highp float;in float s;uniform vec3 uA,uB;out vec4 o;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;float a=(1.-d*2.)*(.25+s*.6);o=vec4(mix(uA,uB,s),a);}`);
  this.brightP=program(gl,`#version 300 es\nout vec2 v;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);v=p;gl_Position=vec4(p*2.-1.,0,1);}`,`#version 300 es\nprecision highp float;in vec2 v;uniform sampler2D uTex;uniform float uThreshold;out vec4 o;void main(){vec3 c=texture(uTex,v).rgb;float l=max(c.r,max(c.g,c.b));o=vec4(c*smoothstep(uThreshold,uThreshold+.55,l),1);}`);
  this.blurP=program(gl,`#version 300 es\nout vec2 v;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);v=p;gl_Position=vec4(p*2.-1.,0,1);}`,`#version 300 es\nprecision highp float;in vec2 v;uniform sampler2D uTex;uniform vec2 uDir;out vec4 o;void main(){vec3 c=texture(uTex,v).rgb*.227027;c+=texture(uTex,v+uDir*1.384615).rgb*.316216;c+=texture(uTex,v-uDir*1.384615).rgb*.316216;c+=texture(uTex,v+uDir*3.230769).rgb*.070270;c+=texture(uTex,v-uDir*3.230769).rgb*.070270;o=vec4(c,1);}`);
  this.compP=program(gl,`#version 300 es\nout vec2 v;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);v=p;gl_Position=vec4(p*2.-1.,0,1);}`,`#version 300 es\nprecision highp float;in vec2 v;uniform sampler2D uScene,uBloom;uniform float uExposure,uBloomAmt,uT,uWarp;out vec4 o;float h(vec2 p){return fract(sin(dot(p,vec2(41.13,289.7)))*43758.5453);}void main(){vec2 uv=v;float ca=.0018+.006*uWarp;float r=texture(uScene,uv+vec2(ca,0)).r;float g=texture(uScene,uv).g;float b=texture(uScene,uv-vec2(ca,0)).b;vec3 c=vec3(r,g,b)+texture(uBloom,uv).rgb*uBloomAmt;c=1.-exp(-c*uExposure);c=pow(c,vec3(.94));float vig=smoothstep(.92,.24,length(uv-.5));c*=.72+.28*vig;c+=(h(uv*vec2(1600,900)+uT)-.5)*.018;o=vec4(c,1);}`);
 }
 setupGeometry(){this.geo={};this.geo.cube=this.upload(cube());this.geo.sphere=this.upload(sphere());this.geo.torus=this.upload(torus());this.geo.cylinder=this.upload(cylinder());this.lineId=0;
  const gl=this.gl,count=7000,pos=new Float32Array(count*3),seed=new Float32Array(count);for(let i=0;i<count;i++){const r=38+Math.random()*150,a=Math.random()*TAU,y=(Math.random()-.5)*90;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=y;pos[i*3+2]=Math.sin(a)*r;seed[i]=Math.random()}this.pVAO=gl.createVertexArray();gl.bindVertexArray(this.pVAO);let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,pos,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,seed,gl.STATIC_DRAW);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,1,gl.FLOAT,false,0,0);gl.bindVertexArray(null);this.pCount=count;
 }
 upload(g){const gl=this.gl,vao=gl.createVertexArray();gl.bindVertexArray(vao);let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(g.p),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(g.n),gl.STATIC_DRAW);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,0,0);let count=g.p.length/3,indexed=false;if(g.i){b=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,b);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(g.i),gl.STATIC_DRAW);count=g.i.length;indexed=true}gl.bindVertexArray(null);return {vao,count,indexed,line:g.line}}
 addLine(points){const id='line'+(++this.lineId);this.geo[id]=this.upload(line(points));return id}
 setupTargets(){const gl=this.gl;this.sceneF=gl.createFramebuffer();this.sceneT=gl.createTexture();this.depth=gl.createRenderbuffer();this.bloomF=[gl.createFramebuffer(),gl.createFramebuffer()];this.bloomT=[gl.createTexture(),gl.createTexture()];}
 allocTargets(){const gl=this.gl,w=this.canvas.width,h=this.canvas.height;gl.bindTexture(gl.TEXTURE_2D,this.sceneT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.bindRenderbuffer(gl.RENDERBUFFER,this.depth);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,w,h);gl.bindFramebuffer(gl.FRAMEBUFFER,this.sceneF);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,this.sceneT,0);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,this.depth);const bw=Math.max(2,Math.floor(w/2)),bh=Math.max(2,Math.floor(h/2));this.bw=bw;this.bh=bh;for(let i=0;i<2;i++){gl.bindTexture(gl.TEXTURE_2D,this.bloomT[i]);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,bw,bh,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.bindFramebuffer(gl.FRAMEBUFFER,this.bloomF[i]);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,this.bloomT[i],0)}gl.bindFramebuffer(gl.FRAMEBUFFER,null)}
 buildScenes(){this.scenes={home:[],projects:[],cyber:[],about:[],contact:[],atlas:[],search:[]};D.projects.forEach(p=>this.scenes['project:'+p.slug]=[]);this.buildHome();this.buildProjects();D.projects.forEach(p=>this.buildProject(p));this.buildCyber();this.buildAbout();this.buildContact();this.buildAtlas();this.buildSearch();}
 obj(route,geo,opt={}){const o={geo,pos:opt.pos||[0,0,0],rot:opt.rot||[0,0,0],scale:opt.scale||[1,1,1],color:hex(opt.color||'#ffffff'),accent:hex(opt.accent||opt.color||'#ffffff'),e:opt.e??.5,a:opt.a??1,add:!!opt.add,spin:opt.spin||[0,0,0],float:opt.float||0,fs:opt.fs||1,phase:opt.phase??Math.random()*TAU,routeTo:opt.routeTo||null,radius:opt.radius||1.4,orbit:opt.orbit||null};this.scenes[route].push(o);if(o.routeTo)this.interactives.push(o);return o}
 ringObj(route,pos,scale,color,rot=[0,0,0],spin=[0,0,0],a=.8){return this.obj(route,'torus',{pos,scale,rot,spin,color,accent:color,e:1.3,a,add:true})}
 buildHome(){for(let i=0;i<6;i++)this.ringObj('home',[0,0,0],[5.2+i*.65,.08,.08],i%2?'#6d5cff':'#ffe29a',[Math.random()*1.5,Math.random()*1.5,Math.random()*1.5],[.06*(i+1),.04*(i%3),.025],.45);this.obj('home','sphere',{scale:[3.1,3.1,3.1],color:'#ff795c',accent:'#ffe29a',e:1.0,a:.36,add:true,float:.18,fs:.6});for(let i=0;i<18;i++){const a=i/18*TAU,r=8.6+(i%3)*1.2;this.obj('home','cube',{pos:[Math.cos(a)*r,Math.sin(a*2.7)*2.2,Math.sin(a)*r],scale:[.13,.13,.7+(i%5)*.18],rot:[a*.3,a,0],spin:[.08,.12,.04],color:i%3===0?'#ff795c':'#ffffff',accent:'#6d5cff',e:.8,a:.7,float:.25,fs:.7})}const pts=[];for(let i=0;i<260;i++){const u=i/259*TAU*2.5,r=6.8+Math.sin(u*3)*1.2;pts.push([Math.cos(u)*r,Math.sin(u*1.7)*2.1,Math.sin(u)*r])}this.obj('home',this.addLine(pts),{color:'#ffe29a',accent:'#ffe29a',e:2,a:.75,add:true,spin:[0,.03,0]});}
 buildProjects(){const path=[];D.projects.forEach((p,i)=>{const a=(i-D.projects.length/2)*1.15,y=(i-1)*4.8,x=Math.sin(i*1.7)*4.8,z=Math.cos(i*1.2)*1.8;path.push([x,y,z]);const c=p.palette[0];this.obj('projects','cube',{pos:[x,y,z],scale:[2.8,1.8,.32],rot:[0,a*.08,a*.05],color:c,accent:p.palette[1],e:.7,a:.88,float:.18,fs:.8,routeTo:'project:'+p.slug,radius:2.4});this.ringObj('projects',[x,y,z],[3.7,.055,.055],p.palette[1],[Math.PI/2,0,0],[0,.15+i*.04,.05],.5);for(let q=0;q<5;q++){const aa=q/5*TAU;this.obj('projects','sphere',{pos:[x+Math.cos(aa)*3.9,y+Math.sin(aa)*2.2,z+Math.sin(aa)*.5],scale:[.12,.12,.12],color:p.palette[2],accent:p.palette[0],e:2,a:.8,add:true,orbit:{center:[x,y,z],radius:3.9,axis:q%2}})}});this.obj('projects',this.addLine(path),{color:'#ffffff',accent:'#ffffff',e:1.4,a:.25,add:true});}
 buildProject(p){const r='project:'+p.slug;if(p.scene==='rf'){for(let i=0;i<5;i++){const a=i/5*TAU,x=Math.cos(a)*7,z=Math.sin(a)*7;this.obj(r,'cylinder',{pos:[x,-1,z],scale:[.6,3,.6],color:'#163f46',accent:p.palette[0],e:.55,a:.94});this.obj(r,'sphere',{pos:[x,2,z],scale:[.75,.75,.75],color:p.palette[1],accent:p.palette[2],e:1.8,a:.92,add:true,float:.15,fs:1.4});for(let k=0;k<3;k++)this.ringObj(r,[x,2,z],[1.3+k*.8,.025,.025],p.palette[0],[Math.PI/2,0,0],[0,.15+k*.05,0],.35)}for(let k=0;k<8;k++)this.ringObj(r,[0,0,0],[2+k*1.2,.035,.035],k%2?p.palette[0]:p.palette[1],[Math.PI/2,0,0],[0,.04+k*.012,0],.26);this.obj(r,'sphere',{scale:[2.2,3.5,2.2],color:'#0d2528',accent:p.palette[0],e:.9,a:.22,add:true})}
  if(p.scene==='neural'){const pts=[];for(let i=0;i<72;i++){const u=Math.random()*TAU,v=Math.acos(2*Math.random()-1),x=Math.sin(v)*Math.cos(u)*4.2,y=Math.cos(v)*5.4,z=Math.sin(v)*Math.sin(u)*3.3;pts.push([x,y,z]);this.obj(r,'sphere',{pos:[x,y,z],scale:[.1+(i%4)*.035,.1+(i%4)*.035,.1+(i%4)*.035],color:i%3?p.palette[0]:p.palette[2],accent:p.palette[1],e:2,a:.75,add:true,float:.12,fs:1.1})}for(let i=0;i<52;i++){const a=pts[i],b=pts[(i*7+13)%pts.length];this.obj(r,this.addLine([a,b]),{color:i%2?p.palette[1]:p.palette[2],accent:p.palette[0],e:1.4,a:.16,add:true})}this.ringObj(r,[0,0,0],[7,.035,.035],p.palette[1],[.6,0,.2],[.07,.05,.02],.3);this.ringObj(r,[0,0,0],[8.2,.025,.025],p.palette[0],[-.4,.7,.1],[-.04,.03,.06],.26)}
  if(p.scene==='forge'){this.obj(r,'cylinder',{scale:[2.5,4.5,2.5],color:'#101710',accent:p.palette[0],e:.38,a:.95});this.obj(r,'cylinder',{scale:[1.25,5.2,1.25],color:p.palette[1],accent:p.palette[0],e:1.8,a:.75,add:true});for(let i=0;i<8;i++)this.ringObj(r,[0,(i-3.5)*1.15,0],[3.6+(i%2)*.6,.09,.09],i%2?p.palette[0]:p.palette[1],[Math.PI/2,0,0],[0,.15*(i%2?1:-1),.02],.65);for(let i=0;i<24;i++){const a=i/24*TAU,rr=7+(i%4)*.6;this.obj(r,'cube',{pos:[Math.cos(a)*rr,Math.sin(a*2)*2.3,Math.sin(a)*rr],scale:[.4,.4,.4],rot:[a,a*.5,0],spin:[.2,.3,.1],color:i%3?p.palette[0]:'#ffffff',accent:p.palette[1],e:.8,a:.7,float:.2,fs:1.2})}}
 }
 buildCyber(){for(let i=0;i<34;i++){const x=(i%7-3)*2.3,y=(Math.floor(i/7)-2)*2.1,z=((i*7)%5-2)*1.5;this.obj('cyber','cube',{pos:[x,y,z],scale:[.45+((i*3)%4)*.2,.45,.45],rot:[i*.2,i*.4,i*.13],spin:[.15,.22,.1],color:i%4===0?'#ff642f':'#252219',accent:'#f4ff38',e:.65,a:.85,float:.16,fs:1.4})}for(let i=0;i<6;i++)this.ringObj('cyber',[0,0,0],[3+i*1.1,.04,.04],i%2?'#f4ff38':'#ff642f',[i*.35,i*.27,i*.18],[.08,.12*(i%2?1:-1),.04],.42);const pts=[];for(let i=0;i<90;i++)pts.push([(i%10-5)*1.6,(Math.floor(i/10)-4)*1.3,Math.sin(i*.7)*2]);this.obj('cyber',this.addLine(pts),{color:'#f4ff38',accent:'#f4ff38',e:1.8,a:.18,add:true});}
 buildAbout(){this.obj('about','sphere',{scale:[2.4,2.4,2.4],color:'#ffb33a',accent:'#fff4bd',e:1.2,a:.72,add:true});D.skills.forEach((s,i)=>{const a=i/D.skills.length*TAU,r=6.5+i*.8;this.obj('about','sphere',{pos:[Math.cos(a)*r,Math.sin(a*1.3)*1.7,Math.sin(a)*r],scale:[.55,.55,.55],color:i%2?'#8b68ff':'#5effb2',accent:'#fff4bd',e:1.2,a:.82,orbit:{center:[0,0,0],radius:r,speed:.12+i*.018,phase:a,y:.8*Math.sin(a)}});this.ringObj('about',[0,0,0],[r,.025,.025],i%2?'#8b68ff':'#5effb2',[Math.PI/2+(i*.08),0,i*.11],[0,.02*(i%2?1:-1),0],.14)});for(let i=0;i<10;i++){const a=i/10*TAU;this.obj('about','cube',{pos:[Math.cos(a)*10,Math.sin(a*2)*2,Math.sin(a)*10],scale:[.16,.16,1.1],rot:[a*.3,a,.2],spin:[.05,.08,.02],color:'#fff4bd',accent:'#8b68ff',e:.65,a:.55})}}
 buildContact(){for(let i=0;i<7;i++){const a=i/7*TAU,r=6.4;this.obj('contact','cube',{pos:[Math.cos(a)*r,Math.sin(a*1.4)*1.5,Math.sin(a)*r],scale:[.6,2.4,.6],rot:[a*.3,a,.7],spin:[.04,.1,.08],color:i%2?'#7dffd6':'#cfc2ff',accent:'#ff8b7c',e:1.2,a:.66,add:true})}for(let i=0;i<5;i++)this.ringObj('contact',[0,0,0],[3+i*1.1,.035,.035],i%2?'#ff8b7c':'#7dffd6',[i*.25,i*.35,i*.17],[.05,.08,.03],.45);this.obj('contact','sphere',{scale:[1.8,3.8,1.8],color:'#24152a',accent:'#7dffd6',e:1.3,a:.3,add:true,float:.25,fs:.8});}
 buildAtlas(){const nodes=[['home',0,4,0,'#ffe29a'],['projects',0,0,0,'#ff2e93'],['cyber',-9,-4,0,'#f4ff38'],['about',0,-7,0,'#5effb2'],['contact',9,-4,0,'#7dffd6']];D.projects.forEach((p,i)=>nodes.push(['project:'+p.slug,(i-1)*7,8,0,p.palette[0]]));nodes.forEach((n,i)=>{this.obj('atlas','sphere',{pos:[n[1],n[2],n[3]],scale:[.9,.9,.9],color:n[4],accent:'#ffffff',e:1.8,a:.9,add:true,float:.2,fs:.8,routeTo:n[0],radius:1.7});this.ringObj('atlas',[n[1],n[2],n[3]],[1.8,.03,.03],n[4],[Math.PI/2,0,0],[0,.12+i*.01,0],.5)});const links=[[[0,4,0],[0,0,0]],[[0,0,0],[-9,-4,0]],[[0,0,0],[0,-7,0]],[[0,0,0],[9,-4,0]]];D.projects.forEach((p,i)=>links.push([[0,0,0],[(i-1)*7,8,0]]));links.forEach(l=>this.obj('atlas',this.addLine(l),{color:'#ffffff',accent:'#ffffff',e:1.2,a:.22,add:true}));}
 buildSearch(){this.searchNodes=[];for(let i=0;i<18;i++){const a=i/18*TAU,r=5+(i%4)*1.5;this.obj('search','cube',{pos:[Math.cos(a)*r,Math.sin(a*3)*2.5,Math.sin(a)*r],scale:[.18,.18,.8],rot:[a,a*.3,0],spin:[.12,.18,.04],color:i%2?'#ffffff':'#ff5b8d',accent:'#77e8ff',e:.9,a:.4,float:.22,fs:1.1})}for(let i=0;i<5;i++){const o=this.obj('search','sphere',{pos:[(i-2)*3.6,0,-1-Math.abs(i-2)*.8],scale:[.72,.72,.72],color:i===0?'#ff5b8d':'#77e8ff',accent:'#ffffff',e:1.8,a:.86,add:true,float:.18,fs:.9+i*.08});this.searchNodes.push(o);this.ringObj('search',o.pos,[1.35,.025,.025],i===0?'#ff5b8d':'#77e8ff',[Math.PI/2,0,0],[0,.12+i*.025,0],.28)}this.ringObj('search',[0,0,0],[6,.04,.04],'#ffffff',[Math.PI/2,0,0],[0,.08,0],.24);}
 setRoute(route,instant=false){if(!this.scenes[route])route='home';if(route===this.route&&!instant)return;this.prevRoute=instant?null:this.route;this.route=route;this.transition=instant?1:0;this.transitionStart=performance.now();this.paletteFrom={a:[...this.palette.a],b:[...this.palette.b],c:[...this.palette.c]};const p=this.presets[route]||this.presets.home;this.paletteTo={a:hex(p.colors[0]),b:hex(p.colors[1]),c:hex(p.colors[2])};this.yaw=0;this.pitch=0;this.zoom=1;}
 setSearchResults(results){if(!this.searchNodes)return;this.searchNodes.forEach((o,i)=>{const hit=results?.[i];o.a=hit?.88:.16;o.e=hit?1.9:.25;o.scale=hit?[.72+(i===0?.18:0),.72+(i===0?.18:0),.72+(i===0?.18:0)]:[.36,.36,.36];o.routeTo=hit?.route||null;o.color=hit?hex(i===0?'#ff5b8d':'#77e8ff'):hex('#3a3a42');});}
  search(query){const q=(query||'').trim().toLowerCase();const pool=[{label:'Origin',route:'home',keywords:'home origin aeter nova'},{label:'Project Archive',route:'projects',keywords:'projects archive work'},{label:'Cybersecurity',route:'cyber',keywords:'ctf security reverse pwn forensics osint'},{label:'About / Identity',route:'about',keywords:'about skills identity zaid tawalbeh robotics ai'},{label:'Contact / Uplink',route:'contact',keywords:'contact github linkedin ctftime social'}].concat(D.projects.map(p=>({label:p.name,route:'project:'+p.slug,keywords:(p.name+' '+p.tagline+' '+p.stack.join(' ')).toLowerCase()})));if(!q)return pool.slice(0,5);const score=s=>{let n=0;s.split(/\s+/).forEach(w=>{if(w.startsWith(q))n+=5;if(w.includes(q))n+=2});return n};return pool.map(x=>({...x,s:score((x.label+' '+x.keywords).toLowerCase())})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,5)}
 setAudioLevel(v){this.audio=clamp(v,0,1)}
 projectWorld(p){const q=projPoint(this.vp,p);return {x:(q[0]*.5+.5)*innerWidth,y:(1-(q[1]*.5+.5))*innerHeight,z:q[2],visible:q[3]>0&&q[2]<1.2}}
 getAtlasAnchors(){if(this.route!=='atlas')return[];return this.scenes.atlas.filter(o=>o.routeTo).map(o=>({route:o.routeTo,pos:this.projectWorld(o._renderPos||o.pos)}))}
 resize(){const dpr=Math.min(devicePixelRatio||1,1.75);this.canvas.width=Math.max(2,Math.floor(innerWidth*dpr));this.canvas.height=Math.max(2,Math.floor(innerHeight*dpr));this.canvas.style.width=innerWidth+'px';this.canvas.style.height=innerHeight+'px';this.allocTargets();}
 bind(){addEventListener('resize',()=>this.resize());addEventListener('pointermove',e=>{this.pointer=[e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2];if(this.drag){const dx=e.clientX-this.dragStart[0],dy=e.clientY-this.dragStart[1];if(Math.abs(dx)+Math.abs(dy)>4)this.dragMoved=true;this.yaw=this.dragYaw-dx*.004;this.pitch=clamp(this.dragPitch-dy*.003,-.55,.55)}});addEventListener('pointerdown',e=>{if(e.button||e.target.closest('.ui,.overlay,.boot'))return;this.drag=true;this.dragMoved=false;this.dragStart=[e.clientX,e.clientY];this.dragYaw=this.yaw;this.dragPitch=this.pitch});addEventListener('pointerup',()=>{if(this.drag&&!this.dragMoved&&this.hover?.routeTo&&this.onNavigate)this.onNavigate(this.hover.routeTo);this.drag=false});addEventListener('wheel',e=>{if(e.target.closest('.ui,.overlay'))return;this.zoom=clamp(this.zoom+Math.sign(e.deltaY)*.07,.72,1.4)},{passive:true});}
 renderObj(o,alpha,t){const gl=this.gl,g=this.geo[o.geo];if(!g)return;let p=[...o.pos],r=[o.rot[0]+o.spin[0]*t,o.rot[1]+o.spin[1]*t,o.rot[2]+o.spin[2]*t];if(o.float)p[1]+=Math.sin(t*o.fs+o.phase)*o.float;if(o.orbit){const a=t*(o.orbit.speed||.15)+(o.orbit.phase||o.phase);p=[Math.cos(a)*o.orbit.radius,(o.orbit.y||0)+Math.sin(a*1.7)*.5,Math.sin(a)*o.orbit.radius]}o._renderPos=p;const M=trs(p,r,o.scale);gl.useProgram(this.meshP);gl.uniformMatrix4fv(gl.getUniformLocation(this.meshP,'uM'),false,M);gl.uniformMatrix4fv(gl.getUniformLocation(this.meshP,'uVP'),false,this.vp);gl.uniform3fv(gl.getUniformLocation(this.meshP,'uC'),o.color);gl.uniform3fv(gl.getUniformLocation(this.meshP,'uA'),o.accent);gl.uniform1f(gl.getUniformLocation(this.meshP,'uE'),o.e*(1+this.audio*.18));gl.uniform1f(gl.getUniformLocation(this.meshP,'uAlpha'),o.a*alpha);gl.uniform1f(gl.getUniformLocation(this.meshP,'uT'),t);gl.bindVertexArray(g.vao);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,o.add?gl.ONE:gl.ONE_MINUS_SRC_ALPHA);if(g.line){gl.drawArrays(gl.LINE_STRIP,0,g.count)}else if(g.indexed){gl.drawElements(gl.TRIANGLES,g.count,gl.UNSIGNED_SHORT,0)}else gl.drawArrays(gl.TRIANGLES,0,g.count);}
 renderRoute(route,alpha,t){if(!route||alpha<=.001)return;const arr=this.scenes[route]||[];arr.forEach(o=>this.renderObj(o,alpha,t))}
 drawBackground(t,warp){const gl=this.gl;gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.useProgram(this.bgP);gl.uniform1f(gl.getUniformLocation(this.bgP,'uT'),t);gl.uniform1f(gl.getUniformLocation(this.bgP,'uWarp'),warp);gl.uniform3fv(gl.getUniformLocation(this.bgP,'uA'),this.palette.a);gl.uniform3fv(gl.getUniformLocation(this.bgP,'uB'),this.palette.b);gl.uniform3fv(gl.getUniformLocation(this.bgP,'uC'),this.palette.c);gl.uniform2fv(gl.getUniformLocation(this.bgP,'uP'),this.pointerSmooth||[0,0]);gl.drawArrays(gl.TRIANGLES,0,3);}
 drawParticles(t){const gl=this.gl;gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.enable(gl.DEPTH_TEST);gl.depthMask(false);gl.useProgram(this.pointP);gl.uniformMatrix4fv(gl.getUniformLocation(this.pointP,'uVP'),false,this.vp);gl.uniform1f(gl.getUniformLocation(this.pointP,'uT'),t);gl.uniform1f(gl.getUniformLocation(this.pointP,'uAudio'),this.audio);gl.uniform3fv(gl.getUniformLocation(this.pointP,'uA'),this.palette.a);gl.uniform3fv(gl.getUniformLocation(this.pointP,'uB'),this.palette.b);gl.bindVertexArray(this.pVAO);gl.drawArrays(gl.POINTS,0,this.pCount);gl.depthMask(true)}
 updateCamera(now){const p=this.presets[this.route]||this.presets.home;let base=[...p.cam],target=[...p.target];const t=this.transition;if(t<1&&this.prevRoute){const pp=this.presets[this.prevRoute]||this.presets.home,e=ease(t);base=[lerp(pp.cam[0],p.cam[0],e)+Math.sin(e*Math.PI)*5,lerp(pp.cam[1],p.cam[1],e)+Math.sin(e*Math.PI)*6,lerp(pp.cam[2],p.cam[2],e)];target=[lerp(pp.target[0],p.target[0],e),lerp(pp.target[1],p.target[1],e),lerp(pp.target[2],p.target[2],e)]}else{const c=Math.cos(this.yaw),s=Math.sin(this.yaw),x=base[0]*c+base[2]*s,z=-base[0]*s+base[2]*c;base=[x*this.zoom,base[1]*this.zoom+this.pitch*8,z*this.zoom]}
  base[0]+=this.pointerSmooth[0]*.5;base[1]+=this.pointerSmooth[1]*.25;this.eye=base;this.view=look(base,target);this.proj=persp(48*Math.PI/180,this.canvas.width/this.canvas.height,.1,500);this.vp=mm(this.proj,this.view)}
 pick(){let best=null,bestD=1e9;const candidates=(this.scenes[this.route]||[]).filter(o=>o.routeTo);candidates.forEach(o=>{const p=this.projectWorld(o._renderPos||o.pos);if(!p.visible)return;const dx=p.x-innerWidth*(this.pointer[0]*.5+.5),dy=p.y-innerHeight*(1-(this.pointer[1]*.5+.5)),d=Math.hypot(dx,dy);if(d<60*o.radius&&d<bestD){best=o;bestD=d}});if(best!==this.hover){this.hover=best;document.body.classList.toggle('is-hovering',!!best);if(this.onHover)this.onHover(best?.routeTo||null)}}
 post(t,warp){const gl=this.gl;gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.viewport(0,0,this.bw,this.bh);gl.bindFramebuffer(gl.FRAMEBUFFER,this.bloomF[0]);gl.useProgram(this.brightP);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.sceneT);gl.uniform1i(gl.getUniformLocation(this.brightP,'uTex'),0);gl.uniform1f(gl.getUniformLocation(this.brightP,'uThreshold'),.68);gl.drawArrays(gl.TRIANGLES,0,3);for(let pass=0;pass<4;pass++){const dst=(pass+1)%2,src=pass%2;gl.bindFramebuffer(gl.FRAMEBUFFER,this.bloomF[dst]);gl.useProgram(this.blurP);gl.bindTexture(gl.TEXTURE_2D,this.bloomT[src]);gl.uniform1i(gl.getUniformLocation(this.blurP,'uTex'),0);gl.uniform2f(gl.getUniformLocation(this.blurP,'uDir'),pass%2?0:1/this.bw,pass%2?1/this.bh:0);gl.drawArrays(gl.TRIANGLES,0,3)}gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.useProgram(this.compP);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.sceneT);gl.uniform1i(gl.getUniformLocation(this.compP,'uScene'),0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,this.bloomT[0]);gl.uniform1i(gl.getUniformLocation(this.compP,'uBloom'),1);const p=this.presets[this.route]||this.presets.home;gl.uniform1f(gl.getUniformLocation(this.compP,'uExposure'),p.exposure);gl.uniform1f(gl.getUniformLocation(this.compP,'uBloomAmt'),p.bloom);gl.uniform1f(gl.getUniformLocation(this.compP,'uT'),t);gl.uniform1f(gl.getUniformLocation(this.compP,'uWarp'),warp);gl.drawArrays(gl.TRIANGLES,0,3)}
 loop(now){const dt=Math.min(.05,(now-this.last)/1000);this.last=now;this.time+=dt;this.pointerSmooth=this.pointerSmooth||[0,0];this.pointerSmooth[0]=lerp(this.pointerSmooth[0],this.pointer[0],.07);this.pointerSmooth[1]=lerp(this.pointerSmooth[1],this.pointer[1],.07);if(this.transition<1){this.transition=clamp((now-this.transitionStart)/this.duration,0,1);if(this.transition===1)this.prevRoute=null}const e=ease(this.transition);['a','b','c'].forEach(k=>{for(let i=0;i<3;i++)this.palette[k][i]=lerp(this.paletteFrom[k][i],this.paletteTo[k][i],e)});this.updateCamera(now);const warp=this.transition<1?Math.sin(this.transition*Math.PI):0;const gl=this.gl;gl.bindFramebuffer(gl.FRAMEBUFFER,this.sceneF);gl.viewport(0,0,this.canvas.width,this.canvas.height);this.drawBackground(this.time,warp);gl.enable(gl.DEPTH_TEST);gl.clear(gl.DEPTH_BUFFER_BIT);this.drawParticles(this.time);const a=e,b=1-e;if(this.prevRoute)this.renderRoute(this.prevRoute,b,this.time);this.renderRoute(this.route,a,this.time);gl.bindFramebuffer(gl.FRAMEBUFFER,null);this.post(this.time,warp);this.pick();if(this.onFrame)this.onFrame({time:this.time,route:this.route,transition:this.transition,atlas:this.getAtlasAnchors()});requestAnimationFrame(this.loop)}
}
window.AeterEngine=Engine;
})();
