import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { AfterimagePass } from 'three/addons/postprocessing/AfterimagePass.js';
import { GlitchPass } from 'three/addons/postprocessing/GlitchPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { projects, skills } from './data.js';

const TAU=Math.PI*2;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const smooth=t=>t*t*(3-2*t);
const hex=x=>new THREE.Color(x);
const tmpV=new THREE.Vector3();

function mat(color,emissive=0.8,rough=.28,metal=.72,opacity=1){
  return new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:emissive,roughness:rough,metalness:metal,transparent:true,opacity});
}
function basic(color,opacity=.6){return new THREE.MeshBasicMaterial({color,transparent:true,opacity,blending:THREE.AdditiveBlending,depthWrite:false});}
function ring(r,t,color,opacity=.65,seg=128){return new THREE.Mesh(new THREE.TorusGeometry(r,t,12,seg),basic(color,opacity));}
function lineRing(r,color,opacity=.25,segments=160){const pts=[];for(let i=0;i<=segments;i++){const a=i/segments*TAU;pts.push(new THREE.Vector3(Math.cos(a)*r,0,Math.sin(a)*r));}return new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color,transparent:true,opacity,blending:THREE.AdditiveBlending,depthWrite:false}));}
function sprite(text,color='#fff',w=680,h=140){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.clearRect(0,0,w,h);x.font='900 40px monospace';x.textAlign='center';x.textBaseline='middle';x.fillStyle=color;x.shadowColor=color;x.shadowBlur=12;x.fillText(text.toUpperCase(),w/2,h/2);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthWrite:false}));s.scale.set(7.8,1.6,1);return s;}
function makeRouteMesh(geometry,material,route){const m=new THREE.Mesh(geometry,material);m.userData.route=route;return m;}
function addMaterialFadeSupport(group){group.traverse(o=>{if(o.material){const arr=Array.isArray(o.material)?o.material:[o.material];arr.forEach(m=>{m.transparent=true;m.userData.baseOpacity=m.opacity??1;});}});}
function opacityOf(group,value){group.traverse(o=>{if(o.material){const arr=Array.isArray(o.material)?o.material:[o.material];arr.forEach(m=>{m.opacity=(m.userData.baseOpacity??1)*value;});}});}

export class ImpossibleMachine{
  constructor(canvas){
    this.canvas=canvas;this.scene=new THREE.Scene();this.clock=new THREE.Clock();this.camera=new THREE.PerspectiveCamera(44,innerWidth/innerHeight,.1,1000);this.camera.position.set(15,7,26);this.scene.add(this.camera);
    this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setSize(innerWidth,innerHeight,false);this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.0;
    this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),1.05,.72,.23);this.composer.addPass(this.bloom);this.after=new AfterimagePass(.9);this.after.enabled=false;this.composer.addPass(this.after);this.glitch=new GlitchPass();this.glitch.enabled=false;this.composer.addPass(this.glitch);this.composer.addPass(new OutputPass());
    this.pointer=new THREE.Vector2();this.pointerSmooth=new THREE.Vector2();this.raycaster=new THREE.Raycaster();this.interactive=[];this.hovered=null;this.drag=false;this.dragMoved=false;this.dragStart={};this.yaw=0;this.pitch=0;this.zoom=1;this.current='home';this.phase=0;this.shock=0;this.transition=null;this.autoOrbit=true;this.quality='high';this.exploded=false;this.audioLevel=0;
    this.palette={a:hex('#ff744f'),b:hex('#8159ff'),c:hex('#fff0ad')};this.paletteTarget={a:this.palette.a.clone(),b:this.palette.b.clone(),c:this.palette.c.clone()};
    this.states={};this.activeGroup=null;this.nextGroup=null;this.animators=[];this.pulses=[];
    this.buildLights();this.buildEnvironment();this.buildPersistentMachine();this.buildStates();this.bind();this.setRoute('home',true);this.resize();this.renderer.setAnimationLoop(()=>this.tick());
  }
  buildLights(){
    this.hemi=new THREE.HemisphereLight('#fff6da','#210d33',1.7);this.scene.add(this.hemi);this.key=new THREE.DirectionalLight('#fff4d7',3.0);this.key.position.set(9,17,13);this.scene.add(this.key);this.lightA=new THREE.PointLight('#ff744f',60,85,2);this.lightA.position.set(-12,9,10);this.scene.add(this.lightA);this.lightB=new THREE.PointLight('#8159ff',70,90,2);this.lightB.position.set(13,-1,-8);this.scene.add(this.lightB);
  }
  buildEnvironment(){
    const v=`varying vec2 vUv;varying vec3 vP;void main(){vUv=uv;vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`;
    const f=`uniform float uT;uniform vec3 uA;uniform vec3 uB;uniform vec3 uC;uniform vec2 uP;uniform float uShock;varying vec2 vUv;varying vec3 vP;
    float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p),q=fract(p);q=q*q*(3.-2.*q);return mix(mix(h(i),h(i+vec2(1,0)),q.x),mix(h(i+vec2(0,1)),h(i+vec2(1,1)),q.x),q.y);}float fbm(vec2 p){float s=0.,a=.5;for(int i=0;i<5;i++){s+=a*n(p);p*=2.03;a*=.5;}return s;}
    void main(){vec2 uv=vUv-.5;float r=length(uv);float angle=atan(uv.y,uv.x);float flow=fbm(vUv*3.2+vec2(uT*.025,-uT*.014)+uP*.12);float iris=.5+.5*sin(angle*7.-uT*.22+flow*5.);vec3 col=mix(uB*.12,uA*.18,flow);col=mix(col,uC*.14,pow(iris,8.)*(1.-smoothstep(.18,.72,r)));float halo=exp(-abs(r-.22-uShock*.18)*18.)*uShock;col+=halo*uC*.7;float grid=pow(max(0.,sin((vUv.x+flow*.04)*150.)*sin((vUv.y-flow*.03)*90.)),22.)*.055;col+=grid*uA;gl_FragColor=vec4(col+.006,1.);}`;
    this.bgMat=new THREE.ShaderMaterial({vertexShader:v,fragmentShader:f,side:THREE.BackSide,uniforms:{uT:{value:0},uA:{value:this.palette.a.clone()},uB:{value:this.palette.b.clone()},uC:{value:this.palette.c.clone()},uP:{value:new THREE.Vector2()},uShock:{value:0}}});this.bg=new THREE.Mesh(new THREE.SphereGeometry(310,48,32),this.bgMat);this.scene.add(this.bg);
    const count=11000,pos=new Float32Array(count*3),seed=new Float32Array(count);for(let i=0;i<count;i++){const r=48+Math.random()*185,a=Math.random()*TAU,z=(Math.random()-.5)*150;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=z;pos[i*3+2]=Math.sin(a)*r;seed[i]=Math.random();}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('aSeed',new THREE.BufferAttribute(seed,1));const pv=`attribute float aSeed;uniform float uT;uniform vec2 uP;varying float vS;void main(){vec3 p=position;float w=sin(uT*.2+aSeed*30.)*.8;p.xz*=1.+w*.003;p.xy+=vec2(uP.x,uP.y)*aSeed*2.;vec4 mv=modelViewMatrix*vec4(p,1.);gl_PointSize=(1.2+aSeed*2.6)*(170./-mv.z);gl_Position=projectionMatrix*mv;vS=aSeed;}`;const pf=`uniform vec3 uA;uniform vec3 uB;varying float vS;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;vec3 c=mix(uA,uB,vS);gl_FragColor=vec4(c,(1.-d*2.)*(.24+vS*.55));}`;this.fieldMat=new THREE.ShaderMaterial({vertexShader:pv,fragmentShader:pf,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uT:{value:0},uP:{value:new THREE.Vector2()},uA:{value:this.palette.a.clone()},uB:{value:this.palette.b.clone()}});this.field=new THREE.Points(g,this.fieldMat);this.scene.add(this.field);
  }
  buildPersistentMachine(){
    this.chassis=new THREE.Group();this.scene.add(this.chassis);
    const outer=ring(10.7,.055,'#ffffff',.18);outer.rotation.x=Math.PI/2.3;this.chassis.add(outer);const outer2=ring(12.2,.028,'#ffffff',.11);outer2.rotation.y=Math.PI/2.4;this.chassis.add(outer2);const rail=lineRing(14,'#ffffff',.11);rail.rotation.x=.55;this.chassis.add(rail);
    for(let i=0;i<18;i++){const a=i/18*TAU;const shard=new THREE.Mesh(new THREE.BoxGeometry(.13,.13,THREE.MathUtils.lerp(.7,2.2,(i%5)/5)),mat(i%2?'#ffffff':'#ff744f',.25,.3,.65,.48));shard.position.set(Math.cos(a)*11.5,Math.sin(a*3)*1.2,Math.sin(a)*11.5);shard.lookAt(0,0,0);this.chassis.add(shard);}
    this.animators.push((t,dt)=>{outer.rotation.z+=dt*.055;outer2.rotation.x-=dt*.04;rail.rotation.y+=dt*.025;this.chassis.rotation.y=Math.sin(t*.08)*.05;});
  }
  stateGroup(id){const g=new THREE.Group();g.userData.id=id;g.visible=false;g.scale.setScalar(.001);this.scene.add(g);this.states[id]=g;return g;}
  buildStates(){this.buildHome();this.buildArchive();projects.forEach(p=>this.buildProject(p));this.buildCyber();this.buildAbout();this.buildContact();Object.values(this.states).forEach(addMaterialFadeSupport);}
  buildHome(){
    const g=this.stateGroup('home');const coreMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uT:{value:0},uA:{value:new THREE.Color('#ff744f')},uB:{value:new THREE.Color('#8159ff')}},vertexShader:`uniform float uT;varying vec3 vN;varying vec3 vP;void main(){vN=normal;vP=position;vec3 p=position;float w=sin(position.y*3.+uT*1.6)+cos(position.x*2.5-uT);p+=normal*w*.13;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`uniform vec3 uA;uniform vec3 uB;varying vec3 vN;varying vec3 vP;void main(){float f=pow(1.-abs(dot(normalize(vN),vec3(0,0,1))),2.);vec3 c=mix(uA,uB,.5+.5*sin(vP.y*2.2));gl_FragColor=vec4(c,.22+f*.72);}`});const core=new THREE.Mesh(new THREE.TorusKnotGeometry(4.15,1.05,240,32,3,5),coreMat);g.add(core);for(let i=0;i<7;i++){const r=ring(6+i*.62,.03,i%2?'#fff0ad':'#8159ff',.24);r.rotation.set(Math.random()*TAU,Math.random()*TAU,Math.random()*TAU);g.add(r);}
    const disciplines=['ROBOTICS','AI','REV','PWN','SYSTEMS','VISION'];disciplines.forEach((d,i)=>{const pivot=new THREE.Group();const a=i/disciplines.length*TAU;pivot.rotation.y=a;g.add(pivot);const crystal=new THREE.Mesh(new THREE.OctahedronGeometry(.72,0),mat(i%2?'#fff0ad':'#ff744f',1.1,.18,.7));crystal.position.set(8.7,Math.sin(i)*1.9,0);pivot.add(crystal);const l=sprite(d,i%2?'#fff0ad':'#ffad8b');l.position.set(8.7,Math.sin(i)*1.9+1.25,0);l.scale.multiplyScalar(.55);pivot.add(l);this.animators.push((t,dt)=>{pivot.rotation.y=a+t*(.08+i*.006);crystal.rotation.x+=dt*.7;crystal.rotation.y+=dt*1.1;});});
    this.animators.push((t,dt)=>{coreMat.uniforms.uT.value=t;core.rotation.y+=dt*.075;core.rotation.x=Math.sin(t*.23)*.17;});
  }
  buildArchive(){
    const g=this.stateGroup('projects');const helix=new THREE.Group();g.add(helix);projects.forEach((p,i)=>{const a=i/projects.length*TAU+Math.PI*.2;const radius=7.4;const holder=new THREE.Group();holder.position.set(Math.cos(a)*radius,(i-(projects.length-1)/2)*3.4,Math.sin(a)*radius);holder.lookAt(0,holder.position.y,0);const mon=makeRouteMesh(new THREE.BoxGeometry(2.4,4.5,.6),mat(p.accent,1.05,.18,.86),`project/${p.slug}`);mon.userData.project=p.slug;holder.add(mon);const halo=ring(1.65,.035,p.accent,.35);halo.rotation.x=Math.PI/2;holder.add(halo);const lab=sprite(p.name,p.accent);lab.position.y=3.0;lab.scale.multiplyScalar(.52);holder.add(lab);helix.add(holder);this.interactive.push(mon);this.animators.push((t,dt)=>{halo.rotation.z+=dt*.45;holder.rotation.z=Math.sin(t*.5+i)*.035;});});
    for(let i=0;i<48;i++){const a=i/48*TAU*3;const bead=new THREE.Mesh(new THREE.SphereGeometry(.07,8,6),basic(i%2?'#19e6ff':'#ff2ea6',.55));bead.position.set(Math.cos(a)*5.5,(i-24)*.32,Math.sin(a)*5.5);g.add(bead);}this.animators.push((t)=>{helix.rotation.y=t*.055;});
  }
  buildProject(p){
    const id=`project/${p.slug}`;if(p.realm==='ruvigil')return this.buildRuVigil(id,p);if(p.realm==='phantom')return this.buildPhantom(id,p);if(p.realm==='elif')return this.buildElif(id,p);return this.buildGenericProject(id,p);
  }
  buildRuVigil(id,p){
    const g=this.stateGroup(id);const floor=lineRing(11,p.accent,.22);g.add(floor);for(let i=0;i<5;i++){const a=i/5*TAU;const tower=new THREE.Group();tower.position.set(Math.cos(a)*6.5,0,Math.sin(a)*6.5);const body=new THREE.Mesh(new THREE.CylinderGeometry(.35,.5,6,10),mat('#e7faff',.18,.2,.82));body.position.y=1;tower.add(body);for(let y=-1;y<4;y++){const rr=ring(1.1+.12*y,.025,p.accent,.32);rr.rotation.x=Math.PI/2;rr.position.y=y*.82;tower.add(rr);}const cap=new THREE.Mesh(new THREE.IcosahedronGeometry(.6,1),mat('#ffca64',1.3,.18,.72));cap.position.y=4.1;tower.add(cap);g.add(tower);this.animators.push((t,dt)=>{tower.rotation.y+=dt*.12;cap.scale.setScalar(1+Math.sin(t*2+i)*.08);});}
    const fieldMat=basic(p.accent,.06);for(let i=0;i<5;i++){const shell=new THREE.Mesh(new THREE.SphereGeometry(3.7+i*.35,32,16,0,TAU,0,Math.PI*.5),fieldMat.clone());shell.scale.y=.7;shell.rotation.y=i*1.1;g.add(shell);this.animators.push(t=>{shell.rotation.y=t*(.08+i*.012);shell.material.opacity=.025+.04*(.5+.5*Math.sin(t*.7+i));});}const human=new THREE.Group();const head=new THREE.Mesh(new THREE.SphereGeometry(.6,20,14),basic('#ffca64',.58));head.position.y=3;human.add(head);const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.72,2,6,12),basic(p.accent,.22));torso.position.y=1.25;human.add(torso);g.add(human);this.animators.push(t=>{human.scale.setScalar(1+Math.sin(t*1.1)*.03);});
  }
  buildPhantom(id,p){
    const g=this.stateGroup(id);const pts=[],links=[];for(let i=0;i<1250;i++){const th=Math.random()*TAU,ph=Math.acos(2*Math.random()-1);let r=4.5*(.82+Math.random()*.2);let x=Math.sin(ph)*Math.cos(th)*r,y=Math.cos(ph)*r*1.2,z=Math.sin(ph)*Math.sin(th)*r*.72;if(y>0.4&&z>2.4&&Math.abs(x)<1.1)z+=.35;if(y>1.0&&Math.abs(x)>.95&&Math.abs(x)<2.3&&z>2.1)z-=.3;pts.push(x,y,z);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));const pm=new THREE.PointsMaterial({color:p.accent,size:.085,transparent:true,opacity:.85,blending:THREE.AdditiveBlending,depthWrite:false});const face=new THREE.Points(geo,pm);g.add(face);for(let i=0;i<70;i++){const j=Math.floor(Math.random()*1250),k=Math.floor(Math.random()*1250);links.push(new THREE.Vector3(pts[j*3],pts[j*3+1],pts[j*3+2]),new THREE.Vector3(pts[k*3],pts[k*3+1],pts[k*3+2]));}const lg=new THREE.BufferGeometry().setFromPoints(links);g.add(new THREE.LineSegments(lg,new THREE.LineBasicMaterial({color:'#8dffd9',transparent:true,opacity:.08,blending:THREE.AdditiveBlending})));const emotions=['HAPPY','SAD','ANGRY','FEAR','NATURAL'];emotions.forEach((e,i)=>{const a=i/5*TAU;const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.48,1),mat(i%2?'#8dffd9':'#ff5bd7',1.2,.15,.55));orb.position.set(Math.cos(a)*7,Math.sin(i)*1.7,Math.sin(a)*7);g.add(orb);const l=sprite(e,i%2?'#8dffd9':'#ff5bd7');l.position.copy(orb.position).add(new THREE.Vector3(0,1,0));l.scale.multiplyScalar(.38);g.add(l);this.animators.push((t,dt)=>{orb.rotation.x+=dt*.8;orb.rotation.y+=dt*1.1;});});this.animators.push((t)=>{face.rotation.y=Math.sin(t*.2)*.25;face.rotation.x=Math.sin(t*.13)*.08;pm.size=.075+.025*(.5+.5*Math.sin(t*1.4));});
  }
  buildElif(id,p){
    const g=this.stateGroup(id);const core=new THREE.Mesh(new THREE.CylinderGeometry(2.1,2.1,5.4,48),mat('#b9ff43',1.1,.12,.94));core.rotation.x=Math.PI/2;g.add(core);for(let i=0;i<6;i++){const r=ring(3.2+i*.78,.10,i%2?'#ff5038':'#b9ff43',.45);r.rotation.set(i*.45,Math.PI/2+i*.2,i*.32);g.add(r);this.animators.push((t,dt)=>{r.rotation.z+=dt*(i%2?.18:-.23);r.rotation.y+=dt*.06;});}for(let i=0;i<10;i++){const panel=new THREE.Mesh(new THREE.BoxGeometry(1.8,.14,3.2),mat(i%2?'#11130c':'#b9ff43',i%2?.08:.35,.28,.8));const a=i/10*TAU;panel.position.set(Math.cos(a)*7,(i%3-1)*1.6,Math.sin(a)*7);panel.lookAt(0,panel.position.y,0);g.add(panel);}const lbl=sprite('ELIF // KERNEL','#b9ff43');lbl.position.set(0,7,0);g.add(lbl);this.animators.push((t,dt)=>{core.rotation.z+=dt*.28;core.scale.setScalar(1+Math.sin(t*2.1)*.035);});
  }
  buildGenericProject(id,p){const g=this.stateGroup(id);const core=new THREE.Mesh(new THREE.DodecahedronGeometry(3.6,1),mat(p.accent,1.2,.12,.8));g.add(core);for(let i=0;i<9;i++){const r=ring(5+i*.35,.03,i%2?p.accent:'#fff',.25);r.rotation.set(Math.random()*TAU,Math.random()*TAU,Math.random()*TAU);g.add(r);this.animators.push((t,dt)=>{r.rotation.y+=dt*(.03+i*.006)});}const l=sprite(p.name,p.accent);l.position.y=6.5;g.add(l);this.animators.push((t,dt)=>{core.rotation.x+=dt*.1;core.rotation.y+=dt*.16;});}
  buildCyber(){
    const g=this.stateGroup('cyber');const frame=new THREE.Group();g.add(frame);for(let i=0;i<40;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(.08,.08,THREE.MathUtils.randFloat(2,6)),basic(i%3?'#faff00':'#ff5a1f',.5));const a=Math.random()*TAU,r=THREE.MathUtils.randFloat(3,10);b.position.set(Math.cos(a)*r,THREE.MathUtils.randFloatSpread(10),Math.sin(a)*r);b.rotation.set(Math.random()*TAU,Math.random()*TAU,Math.random()*TAU);frame.add(b);}const cube=new THREE.Mesh(new THREE.BoxGeometry(4.3,4.3,4.3,7,7,7),new THREE.MeshBasicMaterial({color:'#faff00',wireframe:true,transparent:true,opacity:.4}));g.add(cube);const skull=new THREE.Mesh(new THREE.IcosahedronGeometry(2.2,2),mat('#ff5a1f',.85,.18,.72,.78));g.add(skull);for(let i=0;i<6;i++){const text=sprite(['RIP','RSP','RBP','HEAP','NX','ROP'][i],i%2?'#faff00':'#ff865d');const a=i/6*TAU;text.position.set(Math.cos(a)*8,Math.sin(i*1.7)*2,Math.sin(a)*8);text.scale.multiplyScalar(.5);g.add(text);}this.animators.push((t,dt)=>{cube.rotation.x+=dt*.13;cube.rotation.y-=dt*.18;skull.rotation.y+=dt*.1;frame.rotation.y=t*.055;});
  }
  buildAbout(){
    const g=this.stateGroup('about');const sun=new THREE.Mesh(new THREE.IcosahedronGeometry(2.5,5),mat('#ffd87a',1.5,.35,.28));g.add(sun);skills.slice(0,10).forEach((s,i)=>{const radius=4.5+(i%5)*1.35;const pivot=new THREE.Group();pivot.rotation.x=(i%3-1)*.22;g.add(pivot);const orbit=lineRing(radius,i%2?'#26e6b4':'#7d52ff',.11);pivot.add(orbit);const planet=new THREE.Mesh(new THREE.SphereGeometry(.35+.12*(i%3),16,12),mat(i%2?'#26e6b4':'#7d52ff',.8,.3,.4));planet.position.x=radius;pivot.add(planet);const l=sprite(s.name,i%2?'#a9ffe6':'#c1b1ff');l.position.set(radius,1,0);l.scale.multiplyScalar(.31);pivot.add(l);this.animators.push((t)=>{pivot.rotation.y=t*(.035+i*.002)+i;});});this.animators.push((t)=>{sun.scale.setScalar(1+Math.sin(t*.8)*.045);});
  }
  buildContact(){
    const g=this.stateGroup('contact');const prism=new THREE.Mesh(new THREE.OctahedronGeometry(3.1,0),new THREE.MeshPhysicalMaterial({color:'#f7fff5',emissive:'#88ffd5',emissiveIntensity:.75,roughness:.05,metalness:.15,transmission:.45,thickness:1.2,transparent:true,opacity:.9}));g.add(prism);for(let i=0;i<8;i++){const beam=new THREE.Mesh(new THREE.CylinderGeometry(.015,.035,13,8),basic(i%3===0?'#ff9b78':i%3===1?'#88ffd5':'#6755ff',.5));beam.position.y=6.5;beam.rotation.z=(i-3.5)*.06;g.add(beam);}const portals=['GITHUB','LINKEDIN','CTFTIME','TEAM','LINKTREE','TELEGRAM'];portals.forEach((n,i)=>{const a=i/portals.length*TAU,pivot=new THREE.Group();pivot.rotation.y=a;g.add(pivot);const portal=ring(1.1,.05,i%2?'#88ffd5':'#ff9b78',.55);portal.position.x=7;portal.rotation.y=Math.PI/2;pivot.add(portal);const l=sprite(n,i%2?'#88ffd5':'#ffb6a2');l.position.set(7,1.7,0);l.scale.multiplyScalar(.34);pivot.add(l);this.animators.push((t)=>{pivot.rotation.y=a+t*.07;portal.rotation.z=t*.8;});});this.animators.push((t,dt)=>{prism.rotation.x+=dt*.08;prism.rotation.y+=dt*.19;});
  }
  routePreset(route){
    const p=route.startsWith('project/')?projects.find(x=>route===`project/${x.slug}`):null;
    if(p){const custom={ruvigil:{palette:['#47f5ff','#c67a24','#e7fff9'],cam:[18,7,28],bloom:1.0,exposure:.88},phantom:{palette:['#ff5bd7','#6d44ff','#dffff4'],cam:[17,6,28],bloom:1.12,exposure:.9},elif:{palette:['#b9ff43','#ff5038','#eef9ce'],cam:[18,7,29],bloom:.9,exposure:.8}}[p.realm]||{palette:[p.accent,'#754dff','#fff4d5'],cam:[17,7,28],bloom:1.0,exposure:.9};return custom;}
    return {
      home:{palette:['#ff744f','#8159ff','#fff0ad'],cam:[16,7,27],bloom:.92,exposure:.9},
      projects:{palette:['#ff2ea6','#19e6ff','#fff4cb'],cam:[15,6,28],bloom:1.05,exposure:.87},
      cyber:{palette:['#faff00','#ff5a1f','#f3ffc0'],cam:[18,7,30],bloom:.82,exposure:.72},
      about:{palette:['#ffd87a','#7d52ff','#a9ffe6'],cam:[16,8,30],bloom:.92,exposure:.88},
      contact:{palette:['#88ffd5','#ff9b78','#e6e0ff'],cam:[0,8,30],bloom:1.08,exposure:.88}
    }[route]||this.routePreset('home');
  }
  setRoute(route,instant=false){
    if(!this.states[route])route='home';const next=this.states[route],prev=this.activeGroup;const preset=this.routePreset(route);this.current=route;this.paletteTarget={a:hex(preset.palette[0]),b:hex(preset.palette[1]),c:hex(preset.palette[2])};this.targetBloom=preset.bloom;this.targetExposure=preset.exposure;this.after.enabled=this.quality==='high'&&route.includes('phantom');this.glitch.enabled=this.quality==='high'&&route==='cyber';this.shock=1;this.yaw=0;this.pitch=0;this.zoom=1;
    if(instant){Object.values(this.states).forEach(g=>{g.visible=g===next;g.scale.setScalar(g===next?1:.001);opacityOf(g,g===next?1:0)});this.activeGroup=next;this.nextGroup=null;this.camera.position.set(...preset.cam);this.transition=null;return;}
    next.visible=true;next.scale.setScalar(.001);opacityOf(next,0);this.nextGroup=next;this.transition={t:0,duration:1.45,prev,next,startCam:this.camera.position.clone(),endCam:new THREE.Vector3(...preset.cam)};this.dispatchLayout(route);
  }
  dispatchLayout(route){const side=route==='projects'||route==='about'?'right':route==='contact'?'center':'left';window.dispatchEvent(new CustomEvent('worldlayout',{detail:{route,side}}));}
  setAudioLevel(v){this.audioLevel=THREE.MathUtils.lerp(this.audioLevel,v,.18);}
  toggleExplode(){this.exploded=!this.exploded;return this.exploded;}
  spawnPulse(){const g=new THREE.Group();for(let i=0;i<3;i++){const r=ring(1+i*.35,.035,i%2?this.palette.a:this.palette.c,.65);r.rotation.set(Math.PI/2,i*.7,i*.35);g.add(r);}this.scene.add(g);this.pulses.push({g,life:0});this.shock=Math.max(this.shock,.7);}
  setQuality(q){this.quality=q;const hi=q==='high';this.renderer.setPixelRatio(Math.min(devicePixelRatio,hi?2:1));this.bloom.enabled=hi;this.after.enabled=hi&&this.current.includes('phantom');this.glitch.enabled=hi&&this.current==='cyber';this.resize();}
  reset(){this.yaw=this.pitch=0;this.zoom=1;}
  bind(){addEventListener('resize',()=>this.resize());addEventListener('pointermove',e=>{this.pointer.x=e.clientX/innerWidth*2-1;this.pointer.y=-(e.clientY/innerHeight)*2+1;if(this.drag){const dx=e.clientX-this.dragStart.x,dy=e.clientY-this.dragStart.y;if(Math.abs(dx)+Math.abs(dy)>4)this.dragMoved=true;this.yaw=this.dragStart.yaw-dx*.0042;this.pitch=clamp(this.dragStart.pitch-dy*.003,-.42,.42);}});addEventListener('pointerdown',e=>{if(e.button||e.target.closest('button,a,input,.overlay,.lens'))return;this.drag=true;this.dragMoved=false;this.dragStart={x:e.clientX,y:e.clientY,yaw:this.yaw,pitch:this.pitch};this.spawnPulse();});addEventListener('pointerup',()=>{if(this.drag&&!this.dragMoved&&this.hovered?.userData?.route)window.dispatchEvent(new CustomEvent('worldnavigate',{detail:{route:this.hovered.userData.route}}));this.drag=false;});addEventListener('wheel',e=>{if(e.target.closest('.lens,.overlay'))return;this.zoom=clamp(this.zoom+Math.sign(e.deltaY)*.07,.68,1.4)},{passive:true});}
  hover(){this.raycaster.setFromCamera(this.pointer,this.camera);const live=this.interactive.filter(o=>{let x=o;while(x){if(x.visible===false)return false;x=x.parent;}return true;});const hits=this.raycaster.intersectObjects(live,false),next=hits[0]?.object||null;if(next!==this.hovered){if(this.hovered?.material?.emissiveIntensity!=null)this.hovered.material.emissiveIntensity=this.hovered.userData.baseEI??1;if(next?.material?.emissiveIntensity!=null){next.userData.baseEI=next.material.emissiveIntensity;next.material.emissiveIntensity=2.0;}this.hovered=next;window.dispatchEvent(new CustomEvent('worldhover',{detail:{active:!!next}}));}}
  cameraUpdate(dt,t){const preset=this.routePreset(this.current);if(this.transition){this.transition.t+=dt/this.transition.duration;const u=clamp(this.transition.t,0,1),e=smooth(u);const {prev,next,startCam,endCam}=this.transition;if(prev){const k=1-e;prev.scale.setScalar(Math.max(.001,k*k));prev.rotation.y+=dt*(1.8*e);opacityOf(prev,k);}next.scale.setScalar(.001+(1-.001)*(e*e));next.rotation.y=(1-e)*-1.1;opacityOf(next,e);const arc=startCam.clone().lerp(endCam,e);arc.y+=Math.sin(e*Math.PI)*8;arc.x+=Math.sin(e*Math.PI)*5*(this.pointerSmooth.x||.2);this.camera.position.copy(arc);this.camera.lookAt(0,0,0);if(u>=1){if(prev&&prev!==next){prev.visible=false;prev.scale.setScalar(.001);opacityOf(prev,0);}next.scale.setScalar(1);opacityOf(next,1);this.activeGroup=next;this.nextGroup=null;this.transition=null;}}else{const base=new THREE.Vector3(...preset.cam).multiplyScalar(this.zoom);const q=new THREE.Quaternion().setFromEuler(new THREE.Euler(this.pitch,this.yaw+(this.autoOrbit?Math.sin(t*.08)*.035:0),0,'YXZ'));base.applyQuaternion(q);base.x+=this.pointerSmooth.x*.75;base.y+=this.pointerSmooth.y*.35;this.camera.position.lerp(base,1-Math.pow(.003,dt));this.camera.lookAt(this.pointerSmooth.x*.5,this.pointerSmooth.y*.25,0);}}
  tick(){const dt=Math.min(this.clock.getDelta(),.05),t=this.clock.elapsedTime;this.phase=t;this.pointerSmooth.lerp(this.pointer,.055);this.palette.a.lerp(this.paletteTarget.a,.025);this.palette.b.lerp(this.paletteTarget.b,.025);this.palette.c.lerp(this.paletteTarget.c,.025);this.bgMat.uniforms.uT.value=t;this.bgMat.uniforms.uA.value.copy(this.palette.a);this.bgMat.uniforms.uB.value.copy(this.palette.b);this.bgMat.uniforms.uC.value.copy(this.palette.c);this.bgMat.uniforms.uP.value.copy(this.pointerSmooth);this.shock*=Math.pow(.035,dt);this.bgMat.uniforms.uShock.value=this.shock;this.fieldMat.uniforms.uT.value=t;this.fieldMat.uniforms.uP.value.copy(this.pointerSmooth);this.fieldMat.uniforms.uA.value.copy(this.palette.a);this.fieldMat.uniforms.uB.value.copy(this.palette.b);this.lightA.color.lerp(this.palette.a,.03);this.lightB.color.lerp(this.palette.b,.03);this.hemi.color.lerp(this.palette.c,.018);this.bloom.strength=THREE.MathUtils.lerp(this.bloom.strength,this.targetBloom??1,.04);this.renderer.toneMappingExposure=THREE.MathUtils.lerp(this.renderer.toneMappingExposure,this.targetExposure??.9,.04);this.animators.forEach(fn=>fn(t,dt));if(this.activeGroup){this.activeGroup.children.forEach((o,i)=>{if(!o.userData.explodeBase){o.userData.explodeBase=o.position.clone();const d=o.position.clone();if(d.length()<.1)d.set(Math.sin(i*2.17)+.2,Math.cos(i*1.31)+.15,Math.sin(i*.83+.7));o.userData.explodeDir=d.normalize();}const base=o.userData.explodeBase,target=base.clone().add(o.userData.explodeDir.clone().multiplyScalar(this.exploded?5.5+(i%5)*.65:0));o.position.lerp(target,1-Math.pow(.01,dt));});}this.chassis.scale.setScalar(1+this.audioLevel*.035);this.bloom.strength+=this.audioLevel*.035;this.field.rotation.y=t*.006;this.field.rotation.z=Math.sin(t*.025)*.03;for(let i=this.pulses.length-1;i>=0;i--){const p=this.pulses[i];p.life+=dt;const k=p.life/.9;p.g.scale.setScalar(1+k*7);p.g.children.forEach((r,j)=>{r.material.opacity=Math.max(0,(.62-j*.12)*(1-k));r.rotation.z+=dt*(j+1)});if(k>=1){this.scene.remove(p.g);this.pulses.splice(i,1);}}this.cameraUpdate(dt,t);this.hover();this.composer.render();window.dispatchEvent(new CustomEvent('worldtelemetry',{detail:{phase:t,field:this.current}}));}
  resize(){const w=innerWidth,h=innerHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);this.composer.setSize(w,h);}
}
